### ISSUE TITLE
unit test environment 

### ISSUE THREAD

**Issue by becker89** [e0404/matRad#115]
Apart from Jenkins we should also have a look at Travis CI (https://travis-ci.org/)

**Comment by rainman110** [comment]
Travis is a great CI service, which seamlessly integrated into the GitHub workflow.

Unfortunately, the Travis build nodes don't contain Matlab and I don't see a chance to install it there due to license restrictions.

Jenkins server, on the other hand, can be setup locally. It is not as nicely integrated into GitHub, but comes with a ton of plugins. And since the build nodes run locally, you can install Matlab on it.

Another CI system is appveyor, but it has the same drawback as Travis CI.

**Comment by markbangert** [comment]
We thought about combining travis with ocatve that tests matrad core
functionality that does not rely on graphical output. Do you have any
experience with this?

**Comment by rainman110** [comment]
I'd recommend testing your core algorithms locally on octave first before rolling it out to a CI system like Travis.

Running the stuff on the CI server is no different than running it locally.

We have much experience both with Travis an Jenkins. In combination with GitHub, Travis is great as it supports the pull request workflow. But we never used it together with Matlab or Octave code.

**Comment by markbangert** [comment]
With commit https://github.com/e0404/matRad/commit/309965f258ed7b796ae5d0cae4e01f58d4ff9fab we start using travis for the dev_varRBErobOpt branch.
