### ISSUE TITLE
Fluence optimisation crashes

### ISSUE THREAD

**Issue by Haydnspass** [e0404/matRad#154]
I get a cryptic error message when running a (/the) default plan in matRad.
It crashes in line 190 when ipopt is called. Probably it an issue related to the current Matlab version and / or macOS?

Part of the error message below.

`'/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis->/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices->/System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC->/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata->/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices->/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation->/Applications/MATLAB_R2017a.app/bin/maci64/libmwnativestrings.dylib->/Applications/MATLAB_R2017a.app/bin/maci64/libmwsettingscore.dylib->/Applications/MATLAB_R2017a.app/bin/maci64/libmwservices.dylib->/Applications/MATLAB_R2017a.app/bin/maci64/libmex.dylib->/Users/lucasmueller/Documents/Arbeit/DKFZ/matRad/optimization/ipopt.mexmaci64'
Missing symbol '_xpc_dictionary_get_string' required by
'/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis->/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices->/System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC->/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata->/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices->/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation->/Applications/MATLAB_R2017a.app/bin/maci64/libmwnativestrings.dylib->/Applications/MATLAB_R2017a.app/bin/maci64/libmwsettingscore.dylib->/Applications/MATLAB_R2017a.app/bin/maci64/libmwservices.dylib->/Applications/MATLAB_R2017a.app/bin/maci64/libmex.dylib->/Users/lucasmueller/Documents/Arbeit/DKFZ/matRad/optimization/ipopt.mexmaci64'`

**Comment by markbangert** [comment]
I cannot reproduce this error running the default matRad script with Matlab R2016b on Windows 10. Anybody else with this problem on Matlab R2017a on a different platform? @becker89 have you tried running the default script of the new matRad version on MacOS?

**Comment by becker89** [comment]
Indeed the problem seems to originate from the IPOPT mex file for macOS. Is it the first time you are running Matlab2017a on macOS ? I am using Matlab2016b on macOS and can also not reproduce. Can you check the release notes of Matlab2017a? Maybe they updated/changed something. Another problem could be a missing shared library on system -> check out this page https://de.mathworks.com/help/matlab/matlab_external/invalid-mex-file-error.html  Have you installed Xcode on your Mac?  What I don't understand why the Speech Synthesis framework is involved, which is responsible for voice input.

**Comment by Haydnspass** [comment]
Hm, it seems there were some changes regarding the mex files, however as indicated by https://de.mathworks.com/matlabcentral/fileexchange/53040-ebertolazzi-mexipopt it seems like ipopt is not being well maintained for recent matlab and mac, so I do not really see a solution ...

**Comment by markbangert** [comment]
So would you recommend replacing the Mac and Linux Mex files by the one
provided by ebertolazzi?

Am 15.05.2017 3:21 nachm. schrieb "Lucas" <notifications@github.com>:

Hm, it seems there were some changes regarding the mex files, however as
indicated by https://de.mathworks.com/matlabcentral/fileexchange/
53040-ebertolazzi-mexipopt it seems like ipopt is not being well maintained
for recent matlab and mac, so I do not really see a solution ...

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/e0404/matRad/issues/154#issuecomment-301472796>, or mute
the thread

**Comment by Haydnspass** [comment]
@markbangert 
The precompiled Mex files of ebertolazzi seem to work fine with the mac machine and the most recent Matlab version (tested with boxphantom), so I do not think we need to recompile. No idea about Linux so far.

**Comment by markbangert** [comment]
are there any issues with regard to license etc if we would like to host
these files=

**Comment by Haydnspass** [comment]
There is an eclipse (?) license assigned to the src folder, but nothing to the compiled Mex itself.
Maybe it'd best to implement it as a git submodule (so one stays updated) or we contact him.

**Comment by markbangert** [comment]
what would this mean if we have this as git submodule? would we have more
stuff within our repo than the mex file? or would that just automatically
be pulled from the other repo?

**Comment by Haydnspass** [comment]
Okay hm, maybe my suggestion is overkill. Yeah one has a pointer to a specific commit of a repository, so we would have all the files as well.

**Comment by Haydnspass** [comment]
@markbangert ipopt is under the same license as the (compiled) versions of https://github.com/ebertolazzi/mexIPOPT, so there should be no issues regarding license?

**Comment by markbangert** [comment]
true.

**Comment by markbangert** [comment]
solved with pull request #165 - maybe @wahln will provide an interface to fmincon at a later point in time...
