### ISSUE TITLE
constraint tolerance values

### ISSUE THREAD

**Issue by markbangert** [e0404/matRad#164]
within the ipopt options we specify way to high tolerance levels for constrained optimization. we need to set stricter values here but lets double check first...

**Comment by markbangert** [comment]
@ahmadnish this can also be something for you. for the start it might even just make sense to just use the standard value from https://www.coin-or.org/Ipopt/documentation/node42.html which basically means we could remove these settings so that the defaults are used automatically?!

**Comment by ahmadnish** [comment]
There are two types of constraints defined for IPOPT, the **desired** constraints which meeting each of them would lead to **Solve_Succeeded** output in the command prompt, and the "acceptable" constraints, which meeting them would result in **Solved_to_Acceptable_level** message.
The way these two type of constraint work, is that the moment of the desired constraints has met, the algorithm terminates with the solution, however, **acceptable** constraints need to be met `acceptable_iter` times in a row so that they'll be able to stop the algorithm.

What we have in our `matrad_ipoptOptions.m` file for **desired** constraints are the same as default values. However, neither of these constraints are met in a couple of examples I tried. 

our acceptable constraints are way to high though, all except one, which is the `acceptable_obj_change_tol` being the 

> relative change of the objective function lower than a certain amount for "acceptable_iter" times in a row.

This is what does stop the algorithm and the current amount is 1e-3 and changing this value directly change the converging time. 

So @markbangert  , how do you want to change these values?

**Comment by amitantony** [comment]
I concur. acceptable_obj_change_tol of 1e-4 or 1e-5 yields a little more stable convergence. this does depend on the problem being optimized, a "flatter" objective function naturally needs a lower tolerance and higher max_iter and higher max_cpu_time for it to reach a stable convergence value. For most applications 1e-4 or 1e-5 should suffice.
