### ISSUE TITLE
Small improvement for DijSampling implementation

### ISSUE THREAD

**Issue by rutgerfick** [e0404/matRad#211]
Hello,
It seems that there is a small difference between the matRad_DijSampling.m implementation and the reference paper.

In the implementation, a thresholdDose is separately assigned as the maximum dose for every radiological depth cluster, but the according to the paper the thresholdDose should be the dose at the core radius threshold - which translates to the maximum dose of all clusters together. As a result the subsampling probability becomes dependent on the clusters, and the algorithm subsamples a bit less than it is supposed to.

The fix should be just moving line 116 to above the for loop and setting thresholdDose as max(bixelDoseTail). What do you think?

Best,
Rutger

**Comment by rutgerfick** [comment]
Actually, why is the clustering done here at all? How does it reduce the number of computations?

**Comment by becker89** [comment]
Hi rutgerfick, 
thanks for posting your question. I m not sure but I think you are mixing up the lateral distance and radiological depth. For the moment, consider the lateral dose profile of a single beam profile in a certain depth e.g. z=11mm. Currently, dose values in the inner core (lower than r0) are fully considered. Then we define the thresholdDose as the maximum dose in the tail (which should be the dose at r0). Next, we sample the lateral position according to the paper and assign to these samples the thresholdDose.  Ultimately we repeat this procedure now for certain radiological depth clustered (approx 5mm steps) from 0 to maxRadDepth to cover the complete beam, since the threshold dose migh change with increasing radiological depth. Thus we apply the sampling algorithm from the paper to each depth cluster individually.  Please let me know if this helps or if I misunderstood you.

**Comment by rutgerfick** [comment]
Hi @becker89 , thank you for the explanation! I was indeed mixing up the lateral distance and the radiological depth, I understand what the code is doing now.

I'd like to thank you guys for setting up this really great project! As a newcomer to the field it's really helped me understand the whole radiotherapy pipeline much faster than I could on my own. Next time I make an issue I hope it will actually be an improvement and not my misunderstanding ;-)

**Comment by markbangert** [comment]
Great.so i can close this issue...

Am 11.11.2017 13:53 schrieb "Rutger Fick" <notifications@github.com>:
