### ISSUE TITLE
subarray "w" for recalc of photon plan is missing

### ISSUE THREAD

**Issue by mingersming** [e0404/matRad#214]
Hi there,

the main problem is the missing generation of the subarray "w" in the resultGUI during the DCM import. As you can see in line 143 of the file "matRad_importDicom.m", the array is only created for particles but without the subarray the recalc operation fails for photons.

**Comment by markbangert** [comment]
Thank you @mingersming for bringing this to our attention. We have resolved this issue in https://github.com/e0404/matRad/pull/227 . Furthermore the directDoseCalc Function has been revised in https://github.com/e0404/matRad/pull/226 and in https://github.com/e0404/matRad/pull/219 so that it would also automatically detect the weights in the stf struct. I will close this issue for now. If there is anything fishy with our fix, please do not hesitate and re-open this issue!

Thanks again / Mark
