### ISSUE TITLE
How to change default photons_Generic machine into our own machine ?

### ISSUE THREAD

**Issue by torsionfield** [e0404/matRad#263]
Hello 

I'm a freshman of radiotherapy field. So I don't understand how to change the code related to the machine information, such as "photons_Generic.mat". 

Actually, when I open the file, "photons_Generic.mat", in matlab, the "machine" table comes up.
After I load the table, I could see "Machine.data" table.

In this table, "Machine.data", 

"betas , energy, m, primaryFluence, kernel, kernelPos" field are represented  : 

I'd like to know the meaning of each field, and what I have to do in order to change the default machine into our own machine. 

Thanks

**Comment by mingersming** [comment]
We are sorry, but at the moment you can only use the specific photon pencil beam kernel created from base data for the implemented machine. Please be patient, in a further release of matRad there should be a routine to implement your own base data. 

For now, I will give you a brief explanation of the "Machine.data" content:

+ energy: 'selected' beam energy, according to a LINAC bremsstrahlung spectrum (6MV in case of matRad)
+ m: photon attenuation coefficient for 'selected' energy
+ primaryFluence: Measurement of (rotationally symmetric) primary photon fluence in absence of beam modifying devices (in case of a LINAC: measurement with maximum field width)
+ betas: fitting coefficients for depth dose components of a decomposed TPR (Tissue Phantom Ratio) measurement **[1]**
+ kernel: differential pencil beam kernel for a specific machine; based on primaryFluence and betas as well as TPR and OF (Output Factor) measurements **[1]**
+ kernelPos: radial distance of kernel values in mm

**[1]** Bortfeld, T. , Schlegel, W. and Rhein, B. (1993), Decomposition of pencil beam kernels for fast dose calculations in three‐dimensional treatment planning. Med. Phys., 20: 311-318.

**Comment by torsionfield** [comment]
Thanks a lot for your comment ~

**Comment by markbangert** [comment]
together with @mingersming I started to develop a framework to compute the kernels directly based on measurements as detailed in [1]. Please check out https://github.com/e0404/photonPencilBeamKernelCalc and let us know if you need further help.

**Comment by bwheelz36** [comment]
Hi, I also would be interested in being able to update the machine data, and just wanted to check that this is still the most up to date status? it is the most recent information I have been able to find...
thanks!

**Comment by wahln** [comment]
There's not much change on the matRad side. However, I think there was some more development on the https://github.com/e0404/photonPencilBeamKernelCalc repository, which is able to generate the base data in matRad format from typical measurements.

**Comment by navidRU** [comment]
Dear mingersming and markbangert,

How can I manipulate the original matRad or the respiratory data to be able to commission other photon energies than 6MV?

**Comment by mingersming** [comment]
You can use the already mentioned [photonPencilBeamKernelCalc](https://github.com/e0404/photonPencilBeamKernelCalc) repository.
First, you need the energy dependent base data for your LINAC (TPR measurements, output factors and primary fluence).
Afterwards you make use of the function [ppbkc_generateBaseData.m](https://github.com/e0404/photonPencilBeamKernelCalc/blob/master/ppbkc_generateBaseData.m) and feed it with the name of your machine and a specific base data folder.
(Compare the content of the input dir with the directory structure in the repository, e.g. [synergy folder](https://github.com/e0404/photonPencilBeamKernelCalc/tree/master/synergy), replace the energy comment in the params.dat through your own energy and edit the value of FWHM for some fine-tuning.)
Finally, you copy the created mat file to your matRad working dir, and you are able to use it in the GUI or even command line.

In this way, I have created base data for 15MV and 6MV for an Elekta machine without problems. 
But for FFF the kernel calculation is not correct.

**Comment by naninano1** [comment]
thank you very much for your detailed reply.
The first problem is that I don't know how I can mix the respiratory with the main code, to replace the basic 6MV data. Calling the respiratory files/folders should be done by programming or just copying the respiratory files to a specific folder in the main code?

**Comment by naninano1** [comment]
Thank you very much for your reply.
Today, for starting and testing, I tried to generate mat file for your machine data (Synergy folder).
What I did:
1- I copied the photonPencilBeamKernelCalc contents to matRad folder and added them to matlab environment.
2- Defined the "inputDir" as "...\Synergy\"
3- I ran the ppbkc_generateBaseData.m in matlab

it shows these errors:

_**Not enough input arguments.

Error in ppbkc_generateBaseData (line 18)
machine.meta.name          = name;
 
Undefined function or variable 'kernelResolution'.
Error in ppbkc_generateBaseData (line 128)
machine.data.kernelPos = kernelResolution * [0:(kernelExtension/2-1)];**_

**Comment by mingersming** [comment]
Perfect, that you tried it on your own.But as the error suggest, you missed the first of two parameters for the function ppbkc_generateBaseData.Please specify a name, e.g. ppbkc_generateBaseData('Synergy', '<path_to_folder>')
-------- Ursprüngliche Nachricht --------Von: naninano1 <notifications@github.com> Datum: 23.01.21  14:40  (GMT+01:00) An: e0404/matRad <matRad@noreply.github.com> Cc: mingersming <ensminger.stephan85@gmail.com>, Mention <mention@noreply.github.com> Betreff: Re: [e0404/matRad] How to change default photons_Generic machine into our own machine ? (#263) 
Thank you very much for your reply.
Today, for starting and testing, I tried to generate mat file for your machine data (Synergy folder).
What I did:
1- I copied the photonPencilBeamKernelCalc contents to matRad folder and added them to matlab environment.
2- Defined the "inputDir" as "...\Synergy"
3- I ran the ppbkc_generateBaseData.m in matlab
it shows these errors:
_**Not enough input arguments.
Error in ppbkc_generateBaseData (line 18)
machine.meta.name          = name;
Undefined function or variable 'kernelResolution'.
Error in ppbkc_generateBaseData (line 128)
machine.data.kernelPos = kernelResolution * [0:(kernelExtension/2-1)];**_

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/e0404/matRad/issues/263#issuecomment-766067735",
"url": "https://github.com/e0404/matRad/issues/263#issuecomment-766067735",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by naninano1** [comment]
I appreciate your support. With your guide, I could generate photons_Synergy.mat file. However, I am not sure whether it works. Because there are some general errors related to optimization. I am going to ask it in an appropriate topic.

**Comment by mingersming** [comment]
Glade to hear that you could create a machine file.

**Comment by markbangert** [comment]
Also glad to hear you made the next step and sorry for not chipping in to the discussion earlier. Before clsoing this issue for the time being, though, I wanted to make the point that you have to use your own machine file with care. Please make a couple of validation simulations at different compleity so you know how accurate your model actually is. I would recomment starting with open fileds of different size and at different source to axis distance. Then you can proceed to an IMRT case with one beam, finally multiple beams.

**Comment by Little-Stars520** [comment]
Hi,@markbangert @mingersming
I'm not sure if we can continue this discussion here. 
When I try to run ppbkc_generateBaseData.m, it shows these errors: Function or variable 'getIpOptions' is not recognized.
And then I found that this function does not exist. I would like to ask where this function is placed.

Besides, I found that there are two columns in primflu.dat, "0" and "1", what do these two columns mean.

I have raised an issue, but I would like to ask again here. I would like to know whether MLC is considered in matrad and whether it supports me to change the properties of MLC, such as transmission, curvature, tongue and groove width.

**Comment by wahln** [comment]
Hi @Little-Stars520 ,
the photon dose calculation in matRad is not very advanced and only a pencil-beam dose calculation. MLC information is only considered "indirectly" through the shape of the fitted kernel from corresponding measurements. 
In general, I also would say that when you want to really change MLC parameters and observe the effects, it is also more suitable to model the MLC as a geometry component in a Monte Carlo algorithm, because pencil-beam kernel algorithms in general try to incorporate as many machine details as possible in the precomputation of the kernels. There is some experimental TOPAS branch one could start with, but then you still would need to have a source model / phase-space file for your LINAC.
I really would like to, at some point, improve the photon dose calculation algorithm with better machine models and MLC options, but currently we don't have the resources for that.

**Comment by mingersming** [comment]
Hi.

Please check if the optimization toolbox is included in your Matlab installation. It´s not a function inside the repository.

The first line in primflu.dat means distance (0 mm) from the central axis with a relative primary fluence of 1 (100%).

Best regards.
