### ISSUE TITLE
particle radiological depths

### ISSUE THREAD

**Issue by Phoebegit** [e0404/matRad#268]
Hi,
I find that,in matRad, **partical** radiological depths is computed by 
`radDepths = cumsum(l .* rho{1}); `  ,in which `rho{1}` is electron density 

should this not to be stopping power?

Thanks

**Comment by markbangert** [comment]
Dear Phoebegit,

in matRad we treat relative electron densities and relative stopping power the same way as it scales the pathlength of the radiation inside the patient relative to water. We handle this by converting the HU values from the CT before dose calculation with a custom Hounsfiled lookup table (HLUT). You are right that we are using the same files there, merely because they correspond to standard values. Unfortunately, within the file header of the particle HLUT files we speak of electron densities, which is inconsistent. This has been fixed in commit https://github.com/e0404/matRad/commit/1aed07847b33faacd0068e367f15929c6ff12aea.

Thanks for pointing this out. Let me know if I cna close this issue!

Cheers / Mark

**Comment by markbangert** [comment]
I do not understand what would be the difference between a "real" spr table
and our approach.

Mengya Guo <notifications@github.com> schrieb am Do., 3. Mai 2018, 03:19:

**Comment by markbangert** [comment]
Ah... now I see where you are going.

So the answer is yes! If you want to make accurate dose calculations within matRad you will need to replace the default HLUTs with the tables of your scanner. That holds true for both photons and protons. Potential systematic differences between SPR and e- density are neglected in our open version.

Cheers / Mark
