### ISSUE TITLE
custom sparse matrix format

### ISSUE THREAD

**Issue by markbangert** [e0404/matRad#3]
matlabs built-in sparse matrix format suffers from the following limitations
*only double precision possible (memory issues)
*uses int64 to store the index value which has a maximum value of
intmax('int64')=9223372036854775807
for our purposes
intmax('int32')=2147483647
would suffice
- considering worst case optimization and biological optimization where we have to store multiple values per index a custum format might save even more memory!

the question is can we design a format the still allows for efficient dose calculation - and I am afraid the answer is no.... :(

**Comment by wahln** [comment]
Since this is a won't fix issue anyways, just a very wild idea on this:
1) Create a custom sparse matrix class that overloads the corresponding sparsity-related functions.
2) In these overloaded functions use mex-functions based on the Eigen Template Library's sparse matrix implementation (https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrix.html) which allows all kinds of datatypes for indices and values

I guess this would be too much of an effort....
