### ISSUE TITLE
Increment sigma in water

### ISSUE THREAD

**Issue by Phoebegit** [e0404/matRad#306]
Hello,
   There is a question about the increment of sigma in water (machine.data.sigma) troubled us a long time. Obviously,according to the method calculating sigma in matRad, the increment of sigma in water would not change with the particle source change or SSD change ,and it just calculated by formula. it just related to the energy and depths.
   But we use the MC data to calculate the increment of sigma in water by sqrt((σ（i)^2-σ（1）^2), σ are the **sigma data** in water phantom calculated by MC simulation.  
![image](https://user-images.githubusercontent.com/31639780/48389168-3d273f80-e737-11e8-8af0-4c7bfc635c9b.png)

Obviously ,the sigmas in two method are different.

then we change the position of water phantom to change the air distance before the phantom(SSD),
![image](https://user-images.githubusercontent.com/31639780/48389241-92635100-e737-11e8-90cf-d6e24d55581e.png)

So according to the result of MC, the sigmas in direction x  are different between SSD =400mm and SSD=600mm and SSD variation can change the increment of sigma .
 

**if we just using the increment of sigma in water calculated by formula ,I think that will not get the _exact sigma_ in water compared to the real sigma in water by using the calculation method of sigma in matRad  .**

or the method we calculate **increment sigma** has some problem?

the increment of sigma in water is really  just related to the energy and depths?

**Comment by markbangert** [comment]
That is a good question!

In matRad the \sigmas in water / in the patient underlying the dose calculation are really just a function of the radiological depth and the initial energy. The dependence of an additional broadening of the beam due to different SSDs is only considered by modeling the broadening of the beam in air. This is done at https://github.com/e0404/matRad/blob/master/matRad_calcParticleDose.m#L311 where machine.data(energyIx).initFocus holds a lookup table of measured data in air.

We know that this must be considered an approximation but we have seen that it is enough to just consider the additional broadening in air.

Please let me know if you have more questions. Otherwise I will close this issue...

Kind regards, Mark

**Comment by Phoebegit** [comment]
Would you mind tell me  the accepted difference value  between considering the influence of SSD on sigma in water and not considering SSD?

By the way ,In matRad ,the double Gaussian is about the sigma in water,but I have read a paper in which the double Gaussian is about the sigma in air. So are  there some different in both methods?

Thanks for you patient answer!

**Comment by Phoebegit** [comment]
By the way ,Have you ever considered using matlab parallel calculation in matRad?

**Comment by markbangert** [comment]
1. I do not have a clue about the accepted differences between considering and neglecting the SSD dependence; we took this approach without additional testing from other TPS. Also the very implications of this approach heavily depend on your very beamline. If you are working with a very brilliant beam then you probably do not get away with this but if you have a broad beam this does not matter.

2. Yes we only have a double Gaussian in the patient, in air we consider just one Gaussian (which is thenadded in quadrature to both components of the double Gaussian).

3. Yes we do use the parallel computing toolbox in matlab internally for some applications. As this toolbox is rather expensive, however, we do not include these features in the main release, also because some operations are already intrinsically parallelized by Matlab.

**Comment by Phoebegit** [comment]
Thanks again for your great patience ！
