### ISSUE TITLE
Is dose calculation Ok in photons ?

### ISSUE THREAD

**Issue by rcorredorj** [e0404/matRad#32]
Hi,

I'm trying to calculate Monitor Units after running an optimization method, but I realized something strange. The weights to each segment after sequencing were considerably low. Then I check the range of the beamlets and it seems to me that the values are quite big. For example, when I calculate the dose only for one beam after generating the Dij (using a vector of "ones" for that beam and zeros for the rest), I obtain a max value around 108 Gy in the prostate case. A similar configuration in CERR gives values around 2 Gy what I think is usually the case. Is there probably a bug in the calcPhotonDose code?

Thanks!

RaC

**Comment by markbangert** [comment]
Hey RaC,

currently we do not support absolute dosimetry with the photon dose calculation engine, i.e., the bixel weights have no correspondence to MU. The numbers only make sense relative to each other. If you want to make some abolute dosimetry working yourself you can introduce some normalization, e.g. you can assume 1MU corresponds to a dose of 1Gy at 5cm depth in the center of a 10x10cm² field.

As explained previously, we are in the process of validating both the particle and photon dose calculation engine. At the  moment, we are focussing on protons and carbon ions, photons still need some time. I anticipate that we will start making progress in this regard in the beginning of 2016. 

I apologize that I cannot give you a more satifying answer at the moment. Thank you for your patience,

Mark

**Comment by rcorredorj** [comment]
Thank you for your quick reply. I didn't want to insist that much after you told me that you're working in particles this days, but it was important to confirm that the data was reliable to be used in other pipelines. I will do the normalization you propose me to have a rough idea of the MUs.

Have a good day,

RaC

**Comment by markbangert** [comment]
Don't worry about insisiting. We are totally happy about your diligence. Your comments are very much appreciated and help us a lot to  improve our code. As we just released all the code, however, we have to admit that there is still some work ahead before everything is 100% bullet proof.

As you are very interested in the dose calculation algoroithm I also want to share the following issue with you: Currently we use the same photon scattering kernels (read in from disk) for all geometries. Hence, there is a dependence of the convolution kernels on the source to surface distance that we do not account for. We plan to do so in the future but for the time being this means there will be slight corrections of the scatter kernels due to varying SSDs.

Cheers / Mark

**Comment by rcorredorj** [comment]
Ok, I didn't see this issue and actually I thought that the correction was made here [matRad_calcPhotonDoseBixel] .(https://github.com/e0404/matRad/blob/master/matRad_calcPhotonDoseBixel.m#L69)

```matlab
% now add everything together (eq 19 w/o inv sq corr -> see below)
dose = lat1 .* func_Di(betas(1),radDepths) + ...
       lat2 .* func_Di(betas(2),radDepths) + ...
       lat3 .* func_Di(betas(3),radDepths);

% inverse square correction
dose = dose .* (SAD./geoDists(:)).^2;
```

If I understand correctly, this func_Di should be calculated in runtime as well and not only extracting a value from a precalculated table. Is that right?

**Comment by markbangert** [comment]
Basically it means that we should compute different kernels ppKerneln in https://github.com/e0404/matRad/blob/master/matRad_calcPhotonDose.m depending on the SSD. Right now we use the same kernel data and neglect variations in SSD.

**Comment by rcorredorj** [comment]
Ok, thanks for the clarification.
