### ISSUE TITLE
Run VMC++

### ISSUE THREAD

**Issue by nour-ramadan** [e0404/matRad#351]
Hello,

I would like to try the VMC++ calculation but I cannot seem to locate the exact same library meant to be used in matRad, I would very much appreciate it if you could guide me through the steps of running VMC.

EDIT:

I went through the PDF file of the example, it says I can find the compatible VMC++ files at http://www.cerr.info/download.php but whenever I hit this link it redirects me to the CERR repository on GitHub https://github.com/cerr/CERR and I cannot find the VMC++ files in CERR.

**Comment by markbangert** [comment]
Hi @nour-ramadan and thank you for your interest in matRad. We decided to discontinue support for VMC some time ago exactly because of this issue. We also dont have access to the VMC source code or the binaries and the material is no longer available with CERR. Together with @edoerner we started working on an independent photon MC module that works with matrad out of the box and where everybody has full source code access. This change, however, is only reflected in the development branch at https://github.com/e0404/matRad/tree/dev and there is still some work to be done especially regarding the validation of the code. Maybe @edoerner can comment on this aswell...

Please let me know if you have any further questions. If not I would like to close this issue.

**Comment by nour-ramadan** [comment]
Thank you @markbangert that's been a great help.

I pulled the dev branch to try out the MC module, but when I run the example I'm encountered with 

> Error using matRad_ompInterface
> Abort.
> 
> Error in matRad_calcPhotonDoseMC (line 395)
>     dij.physicalDose{s} = absCalibrationFactor *
>     matRad_ompInterface(cubeRho{s},cubeMatIx{s},ompMCgeo,ompMCsource,ompMCoptions);
> 
> Error in matRad_example4_photonsMC (line 57)
> dij = matRad_calcPhotonDoseMC(ct,stf,pln,cst);

and I believe that's the MEX file so I'm not sure if I'd be able to debug it.
Anyway if you think I should open a new issue for this question or it belongs somewhere else then please feel free to close this issue and I'll post the question later.

Thanks.

**Comment by edoerner** [comment]
hi @nour-ramadan, I just tested the dev branch, with its ompMC module and I am able to execute it without issues. Could you share your working environment? (OS, Matlab version, etc?). In my case my OS is a GNU/Linux Debian 9.0 and Matlab R2018b release.

As @markbangert noticed, we still have work to do regarding the validation of the MC code, in the ompMC side we have conducted some comparisons against EGSnrc (dose profiles, step-by-step comparisons using the debugger, etc), but it is still needed a more exhaustive validation... please let me know if you have any question.

**Comment by nour-ramadan** [comment]
Hi @edoerner, thank you for your reply.

My machine runs Matlab R2018a on Windows 10 64 bit.

However, I tried to delete the MEX file inside the OmpMC directory to force the script to compile it on the fly on my machine and I'm still getting the same error.

**Comment by nour-ramadan** [comment]
Thank you, it worked, I debugged the C code and there was a problem with the file path because it contained spaces.
