### ISSUE TITLE
Hardcoded Gaussian filter width from Siggel's Diploma Thesis

### ISSUE THREAD

**Issue by fengxingweilai** [e0404/matRad#354]
Hello,
     In "matRad_calcPhotonDose.m",there is a note on line 86: "% [mm] / see diploma thesis siggel 4.1.2".
     Can you provide this diploma thesis? I want to learn more about it.
     Thank you.

**Comment by markbangert** [comment]
@rainman110 do you have your thesis anywhere for free download?



fengxingweilai <notifications@github.com> schrieb am Mo., 10. Juni 2019,
04:50:

**Comment by rainman110** [comment]
@fengxingweilai I don't have my thesis online. Just leave me your mail address and I'll send it to you.

**Comment by markbangert** [comment]
@fengxingweilai if you don't want to leave your email here, I can also put you into contact with Martin if you send me an email to contact@matrad.org. For the time being I will close this issue.

Thanks Martin!

**Comment by Songye-CUI** [comment]
http://archiv.ub.uni-heidelberg.de/volltextserver/13411/1/Dissertation_Faculty_Handin.pdf

**Comment by Songye-CUI** [comment]
> http://archiv.ub.uni-heidelberg.de/volltextserver/13411/1/Dissertation_Faculty_Handin.pdf

I am not sure if this is the thesis mentioned in the code. However, I couldn't find why we need to set the default values of sigmaGauss or gaussLimit.

**Comment by wahln** [comment]
The code references to Dr. Siggel's diploma thesis, not his dissertation. But I agree that this reference should be resolved in some way, because we received numerous questions now.

Here is a short explanation: 
The `sigmaGauss` actually corresponds to a _measured_ penumbra with 5mm FWHM, so the actual formula to arrive at `sigmaGauss = 2.123` would be:
`sigmaGauss = FWHM / (2*sqrt(2*ln(2)))`
It is based on assuming collimation of a photon source with finite size, which can be modeled by convolution of the primary fluence with the appropriately wide Gaussian. 
It would probably be more consistent to not hardcode this value into the code, since it will slightly vary accross different machines. My suggestion would be to write the measured FWHM in the photon base data file. @markbangert what do you think?

The other value, `gaussLimit`, is just chosen to ensure that the 2D-gridded filter represents the Gaussian function with sufficient accuracy (comparable to the accepted 5*sigma-boundary used to ensure statistical significance in many physics experiments).

**Comment by Songye-CUI** [comment]
Hello, @wahln! Thanks so much for your explanation and update. Especially, I previously worked on a Brachy project and the EBRT dose calculation algorithm is a bit new to me. Thanks for the excellent matRad work, and best wishes!

**Comment by wahln** [comment]
I will close this issue, since with #461 we will have the possibility to not have this hardcoded, and 2nd it is now explained in the Wiki.
