### ISSUE TITLE
underscore mess up

### ISSUE THREAD

**Issue by mingersming** [e0404/matRad#381]
Issue from line 90 in matRad_importDicomRTDose (dev).

`resultName = strcat(doseTypeHelper,'_',num2str(doseInstanceHelper),beamSuffix);`

I think the additional underscore mess up resultGUI in the end. You will find a 'resultGUI.physicalDose_' after import in your workspace. If you now try to recalc, you get an 'reference to a non existing field 'w_' ' error dialog.

![Unbenannt](https://user-images.githubusercontent.com/34025665/67839878-ed32bb80-faf4-11e9-8c99-c83416f231fe.png)

In my case this error occurs because of a missing InstanceNumber. 
To keep the functionality one could edit **'_',num2str(doseInstanceHelper)** like **beamSuffix** in line 84-86 and add this to line 51 or we should accordingly edit the string concatenation/creation of **resultGUI.w**.

_Originally posted by @mingersming in https://github.com/e0404/matRad/pull/368_

**Comment by wahln** [comment]
Good catch and good solution!
Do you want to/have time to prepare a pull request with the fix?

**Comment by mingersming** [comment]
I will prepare a pull request in the next days.

But could you help me with my first pull request (https://github.com/e0404/matRad/pull/378). 
There is a problem with the travis build.

**Comment by mingersming** [comment]
I´m working on the fix.
But one last thought: is it necessary to create such a dynamic variable in line 147 in matRad_importDicom like 

**resultGUI.w + (_,doseInstanceHelper,beamSuffix)**

At the moment I don´t see a reason for this?
So, it would be better to reduce line 90 in matRad_importDicomRTDose to:

**resultName = doseTypeHelper**

**Comment by wahln** [comment]
I am just looking at this now again. I think the problem here is the following... There might be multiple doses within an RTDose. The instance helper tries to manage this by attaching an Instance number to the dose, which then creates problems with the weight vector suffic when using recalc from the GUI. I propose to keep the instance number from the dicom import but do a better checking in the GUI to avoid this error. So I will for now just fix the GUI to check for an existing appropriate w or instead try to use the "standard" w from resultGUI for recalculation.

**Comment by wahln** [comment]
I have now pushed a fix that handles the weight vs. dose naming (with the underscores) in #461
