### ISSUE TITLE
CalcDoseCallback: Error in dose calculation

### ISSUE THREAD

**Issue by P705** [e0404/matRad#387]
I create .mat file from dicom files. The .mat file load in the matrad gui but this error will appear for dose calculation.
How can i solve this error ?
 
![1](https://user-images.githubusercontent.com/57658660/70516522-62f66200-1b4c-11ea-8328-98f7f361fb5e.JPG)

**Comment by mingersming** [comment]
Please repeat the import and the recalc with the 'dev' branch.

**Comment by P705** [comment]
Whay's 'dev' branch ?

**Comment by mingersming** [comment]
There are plenty of developments of matRad with different progress, bugfixes or content of code.
Therefore, every development has his own branch.

But, here you go: [dev branch](https://github.com/e0404/matRad/tree/dev)
Download this version and repeat the import and recalculation with that branch.

**Comment by P705** [comment]
I download this branch one month ago.
The error shows in first comment will appear in this branch.

**Comment by wahln** [comment]
I think I saw this error once before but I thought it was already fixed a while ago. I will check it as soon as possible.

**Comment by mingersming** [comment]
I had the same thought.

We had the same error a few month ago, but I thought it was fixed with the dev branch.

@P705: Could you please have a look at your cst content. There schould be no entry for all or one structures, 

e.g. `cst{i,5}.visibleColor  %i=1...counter of your structures`

As a dirty fix you could set this variables on your own `cst{1,5}.visibleColor = [1 1 1];`

**Comment by wahln** [comment]
There were circumstances (i.e. when the previous data loading in the GUI was not successful) that could still trigger this error. There's a fix now in the prepareBlaise branch which will soon get integrated into master & dev, so I close this issue.
