### ISSUE TITLE
Error in matRad_calcQualityIndicators

### ISSUE THREAD

**Issue by P705** [e0404/matRad#389]
Hi
How can i handle error attach to the message ?
![1](https://user-images.githubusercontent.com/57658660/70864583-a136bb80-1f68-11ea-9a2a-830d56510d22.JPG)

**Comment by mingersming** [comment]
Hey.I saw the same error but don't have enough time to search for this bug. As a quick fix you can delete some structures from the cst. Look at the command window - before the error displays you can see the last working dvh-structure. Search for it in the cst and delete the next structure(the whole line), close matRad and open the GUI once again.This way fixed the problem.What is your clinical TPS? OTP?
-------- Ursprüngliche Nachricht --------Von: P705 <notifications@github.com> Datum: 15.12.19  15:58  (GMT+01:00) An: e0404/matRad <matRad@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: [e0404/matRad] Error in matRad_calcQualityIndicators (#389) Hi
How can i handle error attach to the message ?


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/e0404/matRad/issues/389?email_source=notifications\u0026email_token=AIDTBQMNTPWMWRNINSKELSLQYZA2RA5CNFSM4J3AP3T2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IASFX4A",
"url": "https://github.com/e0404/matRad/issues/389?email_source=notifications\u0026email_token=AIDTBQMNTPWMWRNINSKELSLQYZA2RA5CNFSM4J3AP3T2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IASFX4A",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by wahln** [comment]
Should have been fixed in #390  
Will close the issue
