### ISSUE TITLE
matRad_interp1 inconsistent extrapolation behaviour

### ISSUE THREAD

**Issue by pamede** [e0404/matRad#401]
I found an inconsistency in matRad_interp1, when in comes to extrapolation. While experimenting with an offset on the radDepths I used dephts in matRad_calcParticleDoseBixel that exceeded max(depths) in the according baseData. I was using single Gauss base data. 
While running this in MatLab did not cause any problems, running the same code in Octave resulted in some sigma values being NaN. Looking into matRad_interp1 I found that in the case of an extrapolation, the function can have three different outputs, depending on the environment and the number of extrapolation points. It can result in either an error, extrapolated values being NaN or extrapolated values using griddedInterpolant.
I am also wondering why this problem is solved for all dose values by the following line,
```
% set dose for query > tabulated depth dose values to zero
X(radDepths > max(depths),1) = 0;
```
but the same is not done for all sigma values in similar form:
```
X(radDepths > max(depths),2) = baseData.sigma(end);
```
Another idea would be to get rid of both of those lines and simply throw an error whenever there is a radDepth, which is greater than max(depths).

**Comment by wahln** [comment]
So matRad_interp1 has managed to maximize its inconsistency going through the branches in the if statement.

1. only one query point --> trying extrapolation throws error
2. griddedInterpolant --> extrapolates
3. legacy interp1 --> trying extrapolation yields NaN

My suggestion would be an optional fourth argument (like interp1 extrapval) to choose the extrapolation behavior, with the default of throwing an error? 
Also: Why does matRad_interp3 not try to use the griddedInterpolant? Is it slower there?
I will fix the stuff, but would like some discussion on the questions first.

**Comment by wahln** [comment]
Just found that for matRad_interp3 griddedInterpolant would work x2-8 quicker.

**Comment by markbangert** [comment]
> Another idea would be to get rid of both of those lines and simply throw an error whenever there is a radDepth, which is greater than max(depths).

I don't think this is a good way forward because we'll have, especially for shallow Bragg peaks, always tons of voxels exceeding the max raddepth in the base data and for performance reasons we want to keep the size of the base data, i.e., the number of interpolation points, small.

**Comment by markbangert** [comment]
> Just found that for matRad_interp3 griddedInterpolant would work x2-8 quicker.

I am confused... For 1D we specifically implemented a switch because GriddedInterpolant is much faster but not available in Octave. I thought that interp3 uses GriddedInterpolant in Matlab if you call it with vectors spanning the three coordinate axis instead of full 3D grids....?!

If there is really such a big performance difference we should def have the Matlab code use GriddedInterpolant. With the decoupling of the dose from the ct grid this interpolation is exercised frequently throughout our code, not only during important....

**Comment by wahln** [comment]
> > Another idea would be to get rid of both of those lines and simply throw an error whenever there is a radDepth, which is greater than max(depths).
> 
> I don't think this is a good way forward because we'll have, especially for shallow Bragg peaks, always tons of voxels exceeding the max raddepth in the base data and for performance reasons we want to keep the size of the base data, i.e., the number of interpolation points, small.

I guess that's kind of the point, because actually we don't experience that scenario in the bixel calculation (the radiological depths are cut before in the calc particle dose). That's why we never realized there's an inconsistent extrapolation in matRad_interp1, because only if there are exceeding rad depths octave crashes the dose calculation because of the extrapolated NaN values with classical interp1.

But also I would probably go for extrapolating IDD with  0's in the bixel calculation and the sigmas with the last sigma (so we don't get div by zero)

**Comment by wahln** [comment]
> > Just found that for matRad_interp3 griddedInterpolant would work x2-8 quicker.
> 
> I am confused... For 1D we specifically implemented a switch because GriddedInterpolant is much faster but not available in Octave. I thought that interp3 uses GriddedInterpolant in Matlab if you call it with vectors spanning the three coordinate axis instead of full 3D grids....?!
> 
> If there is really such a big performance difference we should def have the Matlab code use GriddedInterpolant. With the decoupling of the dose from the ct grid this interpolation is exercised frequently throughout our code, not only during important....

I just checked and you are right, Matlab itself uses griddedinterpolant for interp3. But I guess the preprocessing is much heavier and that's the reason for the performance boosts in my tests.

**Comment by wahln** [comment]
I guess the best thing is to have consistent extrapolation behavior similar to the interp1 function, i.e., yielding NaN's in all cases,  with extrapolation as option.

**Comment by wahln** [comment]
matRad_interp1 should have consistent behavior now in the prepareBlaise branch. I didn't touch matRad_interp3 because I guess the performance gain would be minimal. I will close this issue now.
