### ISSUE TITLE
Running optimization crashes matlab

### ISSUE THREAD

**Issue by regproj** [e0404/matRad#402]
I'm having issues running treatment planning for an example patient (anonymized). I've attached the link to the .mat file and script to reproduce this crash (matlab version 2018b). Just unzip and run matRad.m

I'm wondering if this is due to me incorrectly setting up the objectives/constraints or if there is some other issue I'm not aware of.

https://drive.google.com/file/d/1RAGiR1yqPni02rWf-icwBSIqjxZMpC7N/view?usp=sharing

**Comment by wahln** [comment]
Just to clarify... is it Matlab itself that crashes completely or do you get an error from matRad during optimization? The first one would be related to some segmentation fault in the ipopt.mex* file, which would be quite complicated to debug. 
Anyway, I found a critical bug in the constraint function of the MinMax dose constraint, which unfortunetaly returns a row vector instead of a column vector when using its approximate version with lower **and** upper bounds at the same time. I guess that this was the problem, and unfortunately we were not using this constellation for optimization that much, that's why it slipped through. I will prepare a fix.

**Comment by wahln** [comment]
Check out #403

**Comment by regproj** [comment]
works now, thanks again!
