### ISSUE TITLE
optimization sanity checks

### ISSUE THREAD

**Issue by regproj** [e0404/matRad#404]
I just had a couple quick questions. The first question was I obtained this plot of the objectivve function after running fluence optimization on a prostate case. It seems like the final loss is not necessarily the lowest one. I've attached the figure and am wondering if it looks normal.

The second question was is there some way to check whether the optimization constraints are infeasible or not?
![loss](https://user-images.githubusercontent.com/53584374/75850572-7bb59300-5d9c-11ea-88aa-ed554b3ea9ae.jpg)

**Comment by markbangert** [comment]
Is this the result of the direct aperture optimization following initial
fluence optimization?

regproj <notifications@github.com> schrieb am Mi., 4. März 2020, 07:12:

**Comment by regproj** [comment]
this is following initial fluence optimization

**Comment by markbangert** [comment]
regarding your first question: things look normal. the bahaviour may be related to the interior point optimizer itself and the characteristics of the DAO, i.e., the non-convexity and this discontinuity in the threestep optimization process (initial fluence optimization, sequencing, DAO).

regarding your second question: no.

**Comment by wahln** [comment]
Just some addition to the comments:
This looks to me like an optimization with a lot of constraints. There such jumps can happen due to adaptation of the barrier I think, but as Mark said, there is no safe way to check feasibility upfront. If you want some more output to see plots of constraint violation etc during optimization, you can also try to use the fmincon interface (if you have the optimization toolbox).
