### ISSUE TITLE
How do you set hard dose constraints for the PTV?

### ISSUE THREAD

**Issue by regproj** [e0404/matRad#405]
I've been trying to set dose constraints for the ptv to [72, 88] Gy using the min/max dose constraints. I also have squared overdosing objectives (from 0 Gy) for the OARs and a squared deviation objective (from 80 Gy) for the ptv. Running optimization consistently leads to plans where D98% is around 60 Gy, and I was wondering if this has something to do with using approximate vs voxel-wise as the method. If there is some way to better enforce these ptv dose constraints, any advice would be really helpful. Thanks!

**Comment by wahln** [comment]
There are mainly two things that can lead to this. First, as you pointed out, using the approximate method might yield inaccurate values for the constraint functions and jacobian and therefore lead to violations. 
What I think is the more likely issue is that you might be using a lower dose resolution (e.g. 5mm). The problem here is that the resulting interpolation might lead to voxels not being considered to be part of target in the dose grid while actually containing parts of targets in the ct grid resolution. Since the statistics is performed on the original ct grid resolution, there can now be violations since the constraints could only saw the non-target voxel in optimization. You might try to use a similar resolution on ct & dose grid to avoid this. 
Please let me know if this solves/explains the issue.

**Comment by regproj** [comment]
I currently have the dose resolution set to 5 mm, as you pointed out. I'll try setting it lower to say 2 mm. Would this greatly increase compute?

**Comment by wahln** [comment]
Yes, computation will be substantially slower and need more memory.
An alternative would be to evaluate the statistics themselves on the dose grid (which is, however, not implemented yet) or to use a ct with lower resolution from the beginning.

**Comment by regproj** [comment]
Would you recommend just using the largest dose resolution that allows for the constraints to be satisfied?

**Comment by wahln** [comment]
I don't think there is a unique answer to this question, it depends on what you want to achieve. Downsampling for faster computations always comes at some cost. 

But if you want to be somewhat efficient without too big constraint violations, I guess often used resolutions for the dose grid are around 2.5 to 3 mm's.. I will close this issue then.
