### ISSUE TITLE
Optimizer alternatives

### ISSUE THREAD

**Issue by regproj** [e0404/matRad#414]
Not really an issue, but I was wondering if there were any plans to use other alternatives for IPOpt. Based on my own runs with IPOpt, it seems inverse planning usually takes ~10 min (with a dose resolution of 5x5x5 mm). Were there any future plans to use a convex formualtion/solver to potentially speed up planning? If I were to go about substituting another solver, where would you recommend I start?

**Comment by wahln** [comment]
Some remarks and questions:
- 10min runtimes sound quite long for a (5mm)^3 case.. Just out of curiosity - could you tell me more about your plans# complexity? i.e. #beams, #beamlets, objective/constraint setup? What system are you running on? I would like to understand & reproduce these runtimes.
- We usually observe that evaluation of the gradient / jacobian is the bottleneck for optimization, not the efficiency of the subroutines of the solver itself. This balance might shift when specific or many constraints are used. Currently we are not investigating more code optimizations on that side, but if you are interested to see if you can speed this up, you can look into the implementations within the Objective & Constraint classes and the matRad_OptimizationProblem class.
- Implementing another solver could be done by writing an interface class derived from matRad_Optimizer. This would be comparably straightforward if the solver in question is a non-linear constrained quasi-newton solver. Currently, you can for example use algorithms shipped with fmincon in the Optimization Toolbox by using matRad_OptimizerFmincon (which can be enabled by setting pln.propOpt.optimizer = 'fmincon'. You can compare matRad_OptimizerFmincon and matRad_OptimizerIPOPT to see how interfaces to solvers are implemented. If you know another good solver to interface, we would of course be very happy if this would end up in a contribution to matRad.

**Comment by regproj** [comment]
- Sure, so I have 9 beams and a bixel width of 5 mm. There are 6 objectives (squared underdosing and squared overdosing) and ~12 constraints (MinMaxDose and MinMaxDVH). I also set the tolerance to quite low (~1e-5) and the max iterations to 600 for the optimizer. I'm running it on an ubuntu system with a ryzen 7 2700x cpu
- You mentioned the balance might shift when there are many constraints used.  Approximately how many constraints do you think would be too much?
- I'll take a look. Thanks for your help!

**Comment by regproj** [comment]
So after taking another look, I think I quoted the time for a dose resolution of 2.5x2.5x2.5 mm. The time for 5x5x5 mm is around ~100s. 

However, I did also notice that the time it takes to visualize the dvh is quite long as well ~100s, and I'm guessing that is due to having a large number (~30) of structures. Is there a way to only visualize the dvh for a subset of the structures that doesn't involve the GUI? In the GUI I think that you can uncheck the structures you don't want to see and then calculate the DVH, so there should be a way to do the same in script, right?

**Comment by wahln** [comment]
- For a problem of this complexity it sounds reasonable. Are you using MinMaxDose constraints with exact setting (i.e., evaluation on a voxel basis) by any chance? This is quite computationally demanding, since on a low level it introduces a constraint function for every voxel. I cannot really give an estimate on the tipping-point for run-times / balance, since constraints also differ in time spent in constraint function evluation amongst themselves. I think, however, that IPOPT after optimization prints run-time differentiated by step (i.e. "time spent in objective function evaluation" etc.) Maybe this helps you to analyse the problem.
- There is a variable in the cst cell array, I think it is cst{i,5}.Visible where i is the index of the VOI. if you turn that to 0, it has the same effect as unchecking the structure in the GUI. I am not sure, however, if it speeds up the computation itself in all cases. Alternatively you can also strip the cst with the indices of the volumes you want to compute, e.g. create a cst_tmp = cst(subIx,:), and pass the stripped version to the qi / dvh functions.

**Comment by regproj** [comment]
I'm using the approximate setting. Like you said, I tried the exact one at some point but it slowed down the computation too much that I reverted back.

Stripping the cst cell array and using a temp version sounds like a good idea. I tried the visibility setting again, and it seems that statistics are still calculated for structures that aren't visible. 

Thanks again!
