### ISSUE TITLE
Error importing dose and plan file(photon)

### ISSUE THREAD

**Issue by better0123** [e0404/matRad#417]
![1](https://user-images.githubusercontent.com/50290164/81461888-69fbcc00-91e1-11ea-94fd-c5a12fd9b139.png)
![2](https://user-images.githubusercontent.com/50290164/81461891-6ff1ad00-91e1-11ea-99d4-1e55f74ae3e1.png)
![3](https://user-images.githubusercontent.com/50290164/81461895-754ef780-91e1-11ea-9f25-dd90f67f1c3c.png)
The warning on the diagram appears when the plan is selected.Machine is ‘TR-SN5948’.
I would like to ask why the dose file cannot be imported, and the dose and plan cannot be selected at the same time. Is it because of the accelerator mechine? If so, how to solve it？Thank you!

**Comment by wahln** [comment]
The waring comes from matRad not able to match the RTDose to the RTPlan automatically via dicom UIDs. I am not completely sure why this doesn't match for your dataset, but as the message says it is only a _warning_ - this is usually not a problem in the actual import. You should still be able to import the dose to matRad.

If your import still fails this might be related to the machine.  matRad tries to import field shapes etc, but this might be problematic if no base data file exists for the actual machine (matRad only provides a Generic machine file since we cannot and probably are also not allowed to maintain base-data for all available machines). It can work in some cases, but might not in others. But to help out there, I would need exact error messages from the command line.

Final remark: Import with dicom in matRad, especially plans, is quite unstable since we
1. don't have data for all vendor machines and can't provide it.
2. the data that matRad user's have is too versatile to catch all possible differences in the code
3. we do not aim at providing a fully compatible and robust end-user application but rather a toolkit for research & education. When working with your specific datasets you might need to put in some programming effort to get around data-specific issues, but we are happy to help with general bugs or point you in the right direction.

**Comment by better0123** [comment]
I can't select the plan and dose files at the same time. I can only import the plan, structure and CT 。Or dose, structure and CT.I'll send you the data. Can you check it for me？​


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wahln"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月12日(星期二) 晚上6:13
收件人:&nbsp;"e0404/matRad"<matRad@noreply.github.com&gt;;
抄送:&nbsp;"Linlin Bo"<1121387839@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [e0404/matRad] Error importing dose and plan file(photon) (#417)





 
The waring comes from matRad not able to match the RTDose to the RTPlan automatically via dicom UIDs. I am not completely sure why this doesn't match for your dataset, but as the message says it is only a warning - this is usually not a problem in the actual import. You should still be able to import the dose to matRad.
 
If your import still fails this might be related to the machine.  matRad tries to import field shapes etc, but this might be problematic if no base data file exists for the actual machine (matRad only provides a Generic machine file since we cannot and probably are also not allowed to maintain base-data for all available machines). It can work in some cases, but might not in others. But to help out there, I would need exact error messages from the command line.
 
Final remark: Import with dicom in matRad, especially plans, is quite unstable since we
  
don't have data for all vendor machines and can't provide it.
 
the data that matRad user's have is too versatile to catch all possible differences in the code
 
we do not aim at providing a fully compatible and robust end-user application but rather a toolkit for research &amp; education. When working with your specific datasets you might need to put in some programming effort to get around data-specific issues, but we are happy to help with general bugs or point you in the right direction.

**Comment by better0123** [comment]
I can't select the plan and dose files at the same time. I can only import the plan, structure and CT .Or dose, structure and CT.So it doesn't have the exact error message from the command line when it imports at the same time.I'll send you the data. Can you check it for me？

**Comment by mingersming** [comment]
Just merge the two datasets later in the workspace to one mat file.

**Comment by better0123** [comment]
Thank you, I have combined it according to your method.The prescription dose was then modified.What I want to ask is whether the dose graph when matRad is turned on is the dose from the original data or the dose after matRad calculation.

**Comment by wahln** [comment]
Thanks @mingersming for the simple solution. I could always import doses even if they were not directly matched with the RTPlan. Need to investigate this.

@better0123 : Directly after import the dose cubes displayed should be the one from the dicom import and are stored in the resultGUI-struct (matRad does not automatically do a dose calculation by itself). Look for the naming scheme here: https://github.com/e0404/matRad/wiki/The-result-struct

matRad does also not use a normalized dose prescription - it just creates a set of dummy objectives for planning with some dose level after dicom import. Further, in the matRad GUI we don't yet have a very sophisticated system for comparing plans. If you do a matRad recalculation from the GUI, it might ovewrite the cubes. If you want to do a comparison in the GUI, you can use the "Save to GUI button" to keep a cube in the result structure by giving it a descriptive name. My usual way to go is to create copies of a cube directly in the command window, for example by `resultGUI.physicalDose_old = resultGUI.physicalDose` and then do the matrad dose calculation.
