### ISSUE TITLE
snopt error with GPOPS-II in MATLAB 2020a (MacOS)

### ISSUE THREAD

**Issue by skrdrgn8** [e0404/matRad#422]
I saw a solution to a similar problem for [ipopt on windows](https://github.com/e0404/matRad/issues/408), but I'm running into the following when I try to use snopt:
```
Invalid MEX-file
'/Users/me/Documents/MATLAB/Add-Ons/GPOPS-II/nlp/snopt/snoptcmex.mexmaci64':
dlopen(/Users/me/Documents/MATLAB/Add-Ons/GPOPS-II/nlp/snopt/snoptcmex.mexmaci64,
6): no suitable image found.  Did find:
	/Users/me/Documents/MATLAB/Add-Ons/GPOPS-II/nlp/snopt/snoptcmex.mexmaci64:
        mach-o, but wrong architecture
	/Users/me/Documents/MATLAB/Add-Ons/GPOPS-II/nlp/snopt/snoptcmex.mexmaci64:
        mach-o, but wrong architecture
```
ipopt runs fine, but I'm guessing the snopt mex file is broke in this case. Anyone know of a solution?

**Comment by wahln** [comment]
I think we are the wrong people to ask here... We don't use and have never used snopt at all (since it is not open-source), so you should probably ask their development team. I also never really figured out what exactly the compatability issue this is with the mex interface (Mathworks also has nothing crucial in their changelogs), just that recompiling the binaries helps.
