### ISSUE TITLE
General question about matRad

### ISSUE THREAD

**Issue by P705** [e0404/matRad#426]
matRad supports the planning of intensity-modulated radiation therapy for multiple modalities.
Which part of matRad done the computations for IMRT? The dose calculation by defualt done based on IMRT?

**Comment by wahln** [comment]
matRad by default assumes intensity-modulated treatments. By deafult, matRad_calcPhotonDose and matRad_calcParticleDose execute a beamlet-based (called "bixel" in matRad) computation and return a "dij" struct that stores the dose for each beamlet/bixel at unit-weight, with the weights then being optimized in matRad_fluenceOptimization based on objectives and constraints.  

With some hacks it is also possible to simulate some sort of conformal photon treatment (i.e. one can collapse all beamlets corresponding to one beam shape in the dij). 

For more details on code please check out the techincal documentation in the wiki, the example scripts and the corresponding code in the above mentioned functions.

**Comment by P705** [comment]
Dear friend, i have another basic question.What is basic different between 3d conformal and imrt? which one of these methods more precise?


Sent from Yahoo Mail for iPhone


On Wednesday, July 1, 2020, 20:12, wahln <notifications@github.com> wrote:




matRad by default assumes intensity-modulated treatments. By deafult, matRad_calcPhotonDose and matRad_calcParticleDose execute a beamlet-based (called "bixel" in matRad) computation and return a "dij" struct that stores the dose for each beamlet/bixel at unit-weight, with the weights then being optimized in matRad_fluenceOptimization based on objectives and constraints.

With some hacks it is also possible to simulate some sort of conformal photon treatment (i.e. one can collapse all beamlets corresponding to one beam shape in the dij).

For more details on code please check out the techincal documentation in the wiki, the example scripts and the corresponding code in the above mentioned functions.

**Comment by wahln** [comment]
In one sentence: In conformal treatments you generally do not modulate intensities/fluences via a computerized optimization process, but instead use "static" collimated fields, which usually entails dosimetric disadvantages since this makes it nearly impossible to adequatly conform dose homogeneously to targets with concave shapes (like in the TG119 phantom). 

For the future: This issue tracker should mainly be used for technical issues about the matRad code or to post bug reports and feature requests. This is not for educational questions about radiotherapy. If you want to learn more about different treatment modalities and methods in treatment planning, you probably would be better off with a textbook, a lecture or some papers on that matter. I will close this issue now.
