### ISSUE TITLE
Would enabling MKL for AMD processors speed up IPOPT?

### ISSUE THREAD

**Issue by chh105** [e0404/matRad#449]
I recently came across [this post](https://www.reddit.com/r/matlab/comments/dxn38s/howto_force_matlab_to_use_a_fast_codepath_on_amd/) stating that older maltab versions run very slowly on AMD processors. Apparently, if you enable MKL on an AMD processor, matlab runs much faster. I was wondering if the same sort of logic applies to IPOPT. Does IPOPT enable MKL by default for AMD processors, and if not would there be a significant performance gain if we do enable it?

**Comment by wahln** [comment]
We haven't really investigated this, because the bottleneck in the optimization of radiotherapy problems is usually the evaluation of the objective function and the gradient, and not computing the search direction / step size etc within the optimizer. But certainly, using IPOPT with MKL will be faster, but you need to compile the IPOPT interface with the MKL libraries.

**Comment by wahln** [comment]
Since there is no further action here, we close this issue.
