### ISSUE TITLE
MatRad optimization method

### ISSUE THREAD

**Issue by MohammadrezaMC2** [e0404/matRad#450]
Hello
1_ I have some questions regarding the IPOPT optimization in MatRad. 
Like the image, when ) using IPOPT, you need 1. The objective function 2- Its gradients  3- starting points 4-Jacobian 5-Hessian
I know that the start points are the weights which are optimized by IPOPT but what is the objective function and other parameters(Gradient, Jacobian,....) ?
![Problem](https://user-images.githubusercontent.com/39255756/94557519-89b48f00-026b-11eb-9600-8a2dfa9121f7.png)

2_ In the MatRad_OptimizationIPOPT.m file, the "x" variable used in 

funcs.objective              = @(x) optiProb.matRad_objectiveFunction(x,dij,cst);
funcs.constraints           = @(x) optiProb.matRad_constraintFunctions(x,dij,cst);
funcs.gradient               = @(x) optiProb.matRad_objectiveGradient(x,dij,cst);
funcs.jacobian               = @(x) optiProb.matRad_constraintJacobian(x,dij,cst);
funcs.jacobianstructure = @( ) optiProb.matRad_getJacobianStructure(w0,dij,cst);

it is not declared and how can I access to the value of this parameter?

**Comment by wahln** [comment]
The functions are defined in the class matRad_OptimizationProblem. Is your question even related to radiotherapy optimization or do you want to solve a generic optimization problem like the one shown in your image? if it is the latter, matRad is the wrong software for you and you should check out the implementation of the ipopt matlab interface here: https://github.com/ebertolazzi/mexIPOPT

**Comment by MohammadrezaMC2** [comment]
IPOPT is an optimizer which is used in matRad and it requires some initial parameters to solve and optimize an specific problem you can see it in this webpage:
https://coin-or.github.io/Ipopt/INTERFACES.html

these parameters include 1. Objective function 2.Gradient of the objective function 3. Constraints and... 
matRad defined these parameters in MatRad_OptimizationIPOPT.m file but, it is not clear to me where the "x" variable is given value and what is the objective functions mathematical relationship(like in the website)?

**Comment by wahln** [comment]
Yes, I know what IPOPT is - I implemented the lines of code above... would have been quite impressive otherwise.

Your question seems somewhat fundamental regarding IPOPT and Matlab, and not specifically about matRad. We cannot really answer every fundamental problem about optimization and the programming language. But I can give you some directions.

First, you should understand how anonymous functions in Matlab work:
https://www.mathworks.com/help/matlab/matlab_prog/anonymous-functions.html
Then you should understand how the interface of IPOPT works in Matlab (see my first answer):
https://github.com/ebertolazzi/mexIPOPT

This should answer your question about `x`. Where you can find the implementation of our objective & constraint functions / gradients was already given in the  first reply.

**Comment by markbangert** [comment]
I will close this issue. Please seek assistance with fundamental questions regarding Matlab programming and optimization elsewhere. One more hint from my side: If you want to understand what Matlab code does line by line check out https://de.mathworks.com/help/matlab/matlab_prog/debug-code-in-the-live-editor.html.
