### ISSUE TITLE
Dicom Import Error

### ISSUE THREAD

**Issue by danielkswong** [e0404/matRad#46]
Hello,

When trying to load RS dicom files using Dicom Import, it gave the following error:

Error using  > 
Matrix dimensions must agree.

Error in matRad_convRtssContours2Indices (line 65)
        slicesInMatradCt = find(dicomCtSlicePos+dicomCtSliceThickness/2 > ct.z &
        dicomCtSlicePos-dicomCtSliceThickness/2 <= ct.z);

Error in matRad_importDicom (line 70)
    structures(i).indices = matRad_convRtssContours2Indices(structures(i),ct);

Error in matRad_importDicomGUI>import_button_Callback (line 308)
matRad_importDicom(files);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in matRad_importDicomGUI (line 66)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)matRad_importDicomGUI('import_button_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback

It seems the error was a call to the round2 function in the matRad_convRtssContours2Indices.m file in the following line:

dicomCtSliceThickness = ct.dicomInfo.SliceThickness(round2(ct.dicomInfo.SlicePositions,3)==round2(dicomCtSlicePos,3)); 

Changing the line to the following seemed to fix the problem:

dicomCtSliceThickness = ct.dicomInfo.SliceThickness(round(ct.dicomInfo.SlicePositions/3)*3==round(dicomCtSlicePos/3)*3);

**Comment by markbangert** [comment]
Hi Danielkswong and thanks for sharing this error.

At first glance this problem seems related to https://github.com/e0404/matRad/issues/41 to me. We recently fixed this in the dev branch. Unfortunately we have not merged these changes into the master branch as we are currently also working on a couple of other changes that we would like to have incorporated in one go. Could you please have a look at the link and update me if that might also be the problem in your case? I figure it is a rather common source for bugs during DICOM import because RTSS are often not exactly defined in the same plane like the CTs...

**Comment by markbangert** [comment]
As the changes of the dev branch have been merged into the master and I did not hear any further comments regarding our bug fix I am going to close this issue.
