### ISSUE TITLE
IPOPT on Linux systems

### ISSUE THREAD

**Issue by hadismoazamig** [e0404/matRad#469]
I wanted to implement matRad on a Linux system but I realized that I cannot extract the objective value when implementing the Fluence Map Optimization. After investigation, I realized that It may be because of the incompatibility of IPOPT optimizer with Linux systems.
I am likely experiencing silent incompatibility issues showing up as missing objective value. I guess the OPTI toolbox which contains the IPOPT solver is no longer supported and was a windows OS development project. I am using Matlab 2019.

I would appreciate it if you can help me with this issue.

**Comment by wahln** [comment]
IPOPT is not incompatible with Linux (actually our testing system runs under Linux). However, across different Linux systems there's so much variation that something might not work on your specific system. You can check for the respective mex file (mexa64) if some dependency is missing (mex files are just shared libraries). Or you compile IPOPT and the mex interface yourself. This also has nothing to do with the mentioned OPTI toolbox, since we never used it. Alternatively, you can try to use fmincon from Matlab's optimization toolbox by modifying pln.propOpt.optimizer.
