### ISSUE TITLE
Beam angle optimization 

### ISSUE THREAD

**Issue by pmc-datasci** [e0404/matRad#471]
Hi,
I'm trying to implement a beam angle optimization method using matRad (v2.10.1). I'd like to reuse the stf and dij structures, when optimizing a new beam ensemble, subset of an initial set of beams. I tried to set the beamlet weights corresponding to non used beamlets to zero, but in the end of the optimization, process, all that beamlet weights are given a small (equal) positive value. I wonder to know if there Is a better way to implement stf and dij reutilization, aiming at improving algorithm efficiency.

**Comment by wahln** [comment]
Hi,
I don't fully understand the issue. Where do you set the weights to zero? Do you initialize the optimization with zeros? From what I understand I think the best way would be to write an alternative OptimizationProblem class for BAO (llike it is done for, e.g., DAO) that effectively changes what weight vectors are evaluated within the obejctive functions. 
What you should also consider is that we use an interior-point method for optimization which internally uses logarithmic barrier functions to enforce w staying bigger than zero. Therefore, it is likely that very small positive non-zeros show up in the final result, since at 0 the barrier function is not defined (the barrier function explodes to infinity there)

**Comment by pmc-datasci** [comment]
Hi Wahln,
Thank you for your answer. Yes, I initialize thart weights (from the beams which are in the dij and stf structures but are not in the current beam ensemble) to zero. 
Now I can understand the reason that weights' values are changed is due to the interior point method used, as you have stated. 
As you suggested, I'll try to write an alternative Optimization Problem class for DAO, but I suppose the behaviour will be analogous.
