### ISSUE TITLE
question about generate_stf

### ISSUE THREAD

**Issue by argman** [e0404/matRad#482]
generate_stf.m line 143~145
% project x and z coordinates to isocenter
coordsAtIsoCenterPlane(:,1) = (rot_coords(:,1)*SAD)./(SAD + rot_coords(:,2));
coordsAtIsoCenterPlane(:,2) = (rot_coords(:,3)*SAD)./(SAD + rot_coords(:,2));

after the rotation, rot_coords should be already in a coordinate system which centered at iso-center, so i think this should be 
coordsAtIsoCenterPlane(:,1) = rot_coords(:,1)
coordsAtIsoCenterPlane(:,2) = rot_coords(:,3)

why SAD should be multiplied ?

**Comment by wahln** [comment]
While we are in the correct system here, our coordinates still describe voxel positions in 3D space. Here, we want to project these coordinates to the 2D plane that contains the isocenter and is orthogonal to the incoming beam direction. The projected coordinates are then used to position beamlets. This makes sense, because this equates to the 2D target shape "visible" in the beam's eye view.
Does this make sense to you?

**Comment by wahln** [comment]
Since I can't find a bug here, I will remove the bug label for now.
