### ISSUE TITLE
What does the OP parameter value mean?

### ISSUE THREAD

**Issue by guillermoCabrera** [e0404/matRad#495]
Hi Guys, 

I'm new at matRad, and after having a look at the wiki, I still don't understand what the 'OP' value means. The default value is 2, but that value does not make sense with the description in the wiki. I would really appreciate it if you could explain what the '2' means and (more important) what happens if we change this value.

Cheers
Guillermo

**Comment by wahln** [comment]
Hi,

1) The parameter describes the overlap priority (during optimization). Lower value means higher priority (that might be confusing). A consistent example priority set might be for example: 1 - CTV, 2 - PTV, 3 - OAR(s), 4 - Body Contour. In this sense it does exactly what's written in the Wiki:  

> The overlap priority defines to which VOI a voxel belongs, if there are several VOIs covering the same voxel. If the overlap priority is the same for two VOIs, "overlapping" voxels are considered twice (once for each VOI) during the calculation of the objective function value. Lowest Priority value means the organ overlaps all other organs.

2) the default value of the parameter is not "2". For the default cases included with matRad, the values should be appropriately assigned. When importing a dicom case, the situation is more difficult, since we do not know how to assign priorities without prior knowledge. So we have to make guesses and assign them based on their name, which can of course fail.

**Comment by guillermoCabrera** [comment]
Great! Thanks for your quick reply.

Cheers,
Guillermo
