### ISSUE TITLE
Question about lookup tables

### ISSUE THREAD

**Issue by justingm** [e0404/matRad#500]
Hello!

For the depth dose and lateral beam broadening, how do calculate it when it falls in between values in the lookup table? Do you just interpolate?

Also, I am wondering how the base data for MCsquare was generated. I couldn't find much info about its integration in matRad.

Best,
Justin

**Comment by justingm** [comment]
Thanks for the prompt reply!
I am still a little bit confused about MCsquare. So basically, the purpose of having the MCsquare base data is only for the selection of energy when creating treatment plans in matRad. Once all parameters (such as beam orientation, couch angles, etc) are set, it is deployed to MCsquare for dose calculations and the way I understood it is that the beam model (BDL file) in MCsquare will be used. If I want to use our own beam, then I'd have to create both the base data for matRad and the beam data library for MCsquare. Am i correct?

Best,
Justin

**Comment by wahln** [comment]
Circling back to my previous comment, I might have misunderstood something:
I think you meant what would happen if you would have pencil-beam energy levels that are inbetween the tabulated ones? At the moment, matRad does not interpolate the curves Across energies (because we come from the "synchrotron world" ;-)). So for matRad, you need to create base data for every energy that you want to use in the plan.

Now to your last comment:
In principle, that was the original idea. MCsquare will use its BDL file, and the data is protons_generic_MCsquare is only for the analytical calculation (which was fitted to the respective MCsquare simulations), which would result in you having to create both base data sets to reflect your own machine in Monte Carlo as well as pencil-beam computations.
On the dev_MonteCarlo branch, however, we are trying to merge both worlds / simplifiy this process. For example, we estimate a phase space parameterization from the data in the protons_generic_MCsquare or also allow to give phase space parameterizations in the *.mat base-data file directly (see e.g. #470 ). 
Sorry that I can only give you this half-baked answers at the moment, but you are touching an issue here that is under active development at the moment.

What data do you want to use to create your own base-data in matRad? do you have phase space parameterizations? do you have IDDs + beam widths? Maybe then I could tell you more exactly what parts of the code could be usefeul.

**Comment by justingm** [comment]
No. I meant just the depth dose and the lateral beam broadening values so your initial assumption was correct.

Now about the beam data:
We are still discussing on how to make our own base-data. We will probably use MC simulations as a start to model IDDs and beam widths for our beam line. I will take a look at the dev_MonteCarlo branch and see if I can find my way. If I can't, then maybe I'll get back to you with more questions. :)

Anyway, Is there a way I can receive notifications on new updates for matRad?
