### ISSUE TITLE
fluence matrix in the phantom

### ISSUE THREAD

**Issue by JAMKARAN** [e0404/matRad#507]
How can we have a fluence distribution matrix within the phantom? in fact, matRad calculated the 3D matrix of the dose, but can it also calculate the fluence matrix? 

Thanks

**Comment by wahln** [comment]
matRad has no ready-to-use tool to compute photon/particle fluence distributions within the patient

**Comment by JAMKARAN** [comment]
Thanks for the quick reply 
Can it be extracted from the SVD dose calculation algorithm scripts? Because the algorithm calculates the absorbed dose using the attunated terma (fluence distributions within the phantom/patient) and pencil beam kernels.

**Comment by wahln** [comment]
It could be feasible to modify the matRad_calcPhotonDoseBixel to change the depth dose terms to use only the attenuation term. But I have to admit that I don't have a fool-proof idea from scratch that handles all key variables appropriately. Feel free to dig into the code ;-)

**Comment by JAMKARAN** [comment]
Thanks alot @wahln

**Comment by JAMKARAN** [comment]
Also, I modified the matRad_calcPhotonDoseBixel to change the depth dose terms to use only the attenuation term
```
fluence = func_Di(betas(1),radDepths) + ...
       func_Di(betas(2),radDepths) + ...
       func_Di(betas(3),radDepths);
fluence = fluence .* (SAD./geoDists(:)).^2;
```
Is this correct?

**Comment by wahln** [comment]
I don't know, but I doubt that such a hack is from scratch physically correct. What does the result look like?

**Comment by JAMKARAN** [comment]
A fluence distribution is obtained but I do not know how to evaluate it? I'm not sure this method also achieves scattering due to interaction within the phantom.

**Comment by JAMKARAN** [comment]
Do you have a suggestion to find the scattering matrix in the patient/phantom?

**Comment by wahln** [comment]
No I don't have any further suggestions out of the box. 
Since the algorithm is based on "full" kernels and not point-spread kernels, the exact fluence is just not available within matRAd during dose calculation. Only the primary fluence is available. 
Since the kernel's are fitted to measurements, I guess that it will also stay difficult to use the deconvolution approach on the given base data. I think the best way would be to directly work with an MC algorithm that can score the photon fluence.
