### ISSUE TITLE
[BUG] error in matRad_generateStf

### ISSUE THREAD

**Issue by fengxingweilai** [e0404/matRad#510]
I generate a pln file from the rt-plan, and then plan to generate an stf file :

rtPlanFiles{1} = 'RP.200905624.3F_IMRT.dcm';
pln = matRad_importDicomRTPlan(ct, rtPlanFiles, 0);
now, pln.propStf.bixelWidth = 'field';
when I used 'stf = matRad_generateStf(ct,cst,pln,1)' to generate an stf file, The code doesn't work properly. Code prompt an error:  'bixel width (spot distance) needs to be a real number [mm] larger than zero';

so, how to use rt-plan to generate the stf file, the use the 'matRad_calcDoseDirect' to calculate the dose.

thanks.

**Comment by wahln** [comment]
From what I see this error is intended behavior. When matRad imports a photon RTPlan, it should import the collimation / shape information, and directly create an stf during the import that stores the given field information. That's why it sets the `bixelWidth = 'field'`, because the stf already contains a segmented field so we don't do a bixel-based dose calculation.

Long story short: 
Usually you would not run `matRad_generateStf(...)` after an RTPlan import, because the `stf` including sequenced fields should already be there. you should directly run `matRad_calcDoseDirect(...)`. If after import the `stf` is not yet there and the `bixelWidth` is still set to field, that's indeed (at least to some extent) a bug.
