### ISSUE TITLE
Question about dicom import

### ISSUE THREAD

**Issue by zeng99-jiu** [e0404/matRad#513]
Hello, I have a question that when I try to import ct dicom file  with its default resolution, the output should be a 512x512x99 matrix but a 511x511x99 matrix is generated instead. I have read the 'matRad_importDicomCt.m 'and 'matRad_interpDicomCtCube.m' and I think the ct cube's dimensions be changed in 'matRad_interpDicomCtCube.m'. But I don't know why it would be like this since I do not change the output resolution. Or is there any solution that can help to get the right dimension matrix?

**Comment by wahln** [comment]
Hi! This is indeed a bug, which recently also @ahmadnish encountered when importing DICOM via the graphical importer, which was due to rounding issues of the resolution in the GUI which triggered interpolation (see #503 and the fix #509). The fix was merged into the [dev](https://github.com/e0404/matRad/tree/dev) branch, so best way to work around this bug is the code from there!

**Comment by zeng99-jiu** [comment]
Thanks for your quick reply! It helps me a lot!
