### ISSUE TITLE
Error with matRad_calcDVH()

### ISSUE THREAD

**Issue by fratomtom** [e0404/matRad#530]
Hi, I am writing to find out how to handle the following error that I get when calculating DVHs on Dicomworks-imported structures:

Index exceeds the number of array elements (13983237).

Error in matRad_calcDVH>getDVHPoints (line 74)
doseInVoi   = doseCube(indices);

Error in matRad_calcDVH (line 62)
    dvh(i).volumePoints = getDVHPoints(cst, i, doseCube, doseGrid, dvhType);

I understand that the issue arises when doseInVoi looks for structure indices that do not correspond to any voxel in doseCube. Being the dose grid resolution lower compared to that of the CT on which structures are contoured, it is not clear to me how to solve this issue. Would it be enough passing a doseGrid to the calcDVH function?

Thank you,

regards

**Comment by fratomtom** [comment]
I realised that the problem could be solved by using the matRad function resizeCstToGrid. I used that function by passing the CT x,y,z vectors, as well as dose grid vectors that I derived from the RD dicom (starting from ImagePositionPatient and voxel size).

I am now able to calculate and plot DVHs, event though there seems to be some artefact. I attach below a plot of the GTV-DVH:

![image](https://user-images.githubusercontent.com/43438416/144391166-531b66e4-6d77-468b-9c32-959a41e85630.png)


As you can see, the DVH seems to be somehow "unbalanced" toward low dose values, and it looks far from a target DVH.

Do you have any idea what could be the source of this issue?

Thank you again

**Comment by wahln** [comment]
Can you give me the code snippet leading up to your calland plotting of the DVH?
One thing to know: matRad usually stores imported and calculated dose cubes resampled to ct resolution in the workspace variable `resultGUI`. The easiest way to the plot and show plan statistics is `[dvh,qi] = matRad_indicatorWrapper(cst,pln,resultGUI);`

**Comment by fratomtom** [comment]
Thank you, I didn't notice that when importing the dose from a Dicom file it is automatically resampled on the ct grid, that's useful! One question related to the indicatorWrapper: how could one use it in case only dose files are imported, but not plans? Should one declare a "fake" plan? Obviously, in this case only analysis would be performed, and no dose calculation/optimization. 

Thank you!

**Comment by wahln** [comment]
- yeah, so far there is no option during the DICOM import to import with both grids. It's something that we should probably implement, so that both the resampled and the original dose cube are available. However, you can do a second import and check the "use dose grid" function if you want to import the files in the dose grid resolution and store them in a different mat file.
- the indicatorWrapper is somewhat badly designed. matRad_calcDVH and matRad_showDVH both work without plan (or for the latter pln = []), however the indicatorWrapper does not, because it needs some plan information (like number of fractions).  you can create a dummyPln with the values required: `dummyPln.numOfFractions = 1; dummyPln.propOpt.bioOptimization = 'none';`
