### ISSUE TITLE
CakcDoseCall back: Error in steering file generation!

### ISSUE THREAD

**Issue by LGDi** [e0404/matRad#541]
This error window pops up when I use my own data for calculation
![1](https://user-images.githubusercontent.com/96415745/148182739-16921cff-4736-4775-881f-9956e961f349.png)
At the same time, this error appears in the command window of MATLAB.
![2](https://user-images.githubusercontent.com/96415745/148183031-d4ffc293-b53b-4b20-877c-7a28c63b4614.png)

**Comment by wahln** [comment]
About the warning in the command line: It seems to occur when matRad computes where to cut-off the dose calculation laterally (i.e., omit the computation of too small dose contributions for performance). This warning usually points towards an inconsistency in the base data file.
The error is not clear to me. Could you run your set-up in a script so the full error gets printed to the command line?
That means, after definition of the plan parameters (which you also can do in the GUI), go to the command line and run
`stf = matRad_generateStf(ct,cst,true);`
and then
`dij = matRad_calcParticleDose(ct,stf,pln,cst);`
Let me know in which step the error occurs and its output to the cmd.

**Comment by LGDi** [comment]
This is the result after running according to your requirements.
![image](https://user-images.githubusercontent.com/96415745/148773281-731ca241-fc3b-4924-9f85-3ad33303ae7c.png)

**Comment by wahln** [comment]
It looks like your computation is set up for photons (i.e., radiation mode is set to "photons"). That's why the photon dose calculation runs through, and the particle dose calculation does not...

**Comment by LGDi** [comment]
![image](https://user-images.githubusercontent.com/96415745/148776813-adfdf56d-25d7-4d25-a14d-fbb6c3a3d5f8.png)
![image](https://user-images.githubusercontent.com/96415745/148776845-e1111ca0-cb9c-463e-ab3e-1ac40222060d.png)
![image](https://user-images.githubusercontent.com/96415745/148776884-04b0aeee-8a99-4940-a459-ff75caf66222.png)

**Comment by LGDi** [comment]
How should I solve this problem ? Hope to get your point.

**Comment by wahln** [comment]
I need some more information:
1) I assume you replaced the protons_Generic.mat with your own data? (While this should not induce problems, it is still not advised - rather generate a new mat file, e.g. protons_myData.mat and then select "myData" as machine)
2) what geometry are you running on? are you using your own patient data or one of matRad's phantoms? If you are using your own patient data, does it work on BOXPHANTOM.mat or TG119.mat supplied with matRad?

**Comment by LGDi** [comment]
I used my own database, but I replaced the original protons _ Generic. mat file for preliminary simple verification. In my own database, only 109 lines of data, compared with the previous reduced a few lines.
In addition, I detected it on TG119.mat supplied with matRad.

**Comment by LGDi** [comment]
The reason why I replaced rather than built a new database was that I thought this database would be used in the following dose calculation and optimization, but I had not found a way to use it.

**Comment by LGDi** [comment]
I running the following after `matRad_calcLateralParticleCutOff(machine,0.95,stf(1),true);`，I can get some pictures,is there a file to explain the contents of the diagram？
If I want to create a file protons_MyMcahine.mat,what parameters do I need to know about my machine ?Where can I view the default machine data information ?

**Comment by wahln** [comment]
There is no file that explains the content apart from the source file itself. In principle the images shows at which lateral distance the dose calculation decides not to compute dose points anymore because the dose becomes too low. 

Regarding the second question - I don't really understand what you are asking. The file needs the same _structure_ as the default machine, which is given in proton_Generic.mat (unless you have overwritten it with a modified version), but with your data. So for every energy your machine has available, you create an entry that has all the parameters (energy, peakPos, range, depth, Z, etc..). There is some stuff that is not strictly necessary (LET for example). Note that currently we do not do interpolation between provided energies, which may be expected by some users working with cyclotrons data - you need to provide an entry for each energy you want to plan with, If interpolation between energies is of interest to you, let us know.
