### ISSUE TITLE
Question about LET in protons_Generic base data file 

### ISSUE THREAD

**Issue by jeimzos** [e0404/matRad#542]
Dear all, 

I would like to simulate LETd alongside dose from a dicom proton plan import (from our own machine). I have successfully performed the dicom import, and would like to create a custom base data file for our own machine. However, I have some questions regarding the LET values in the 1d arrays of the protons_Generic base data file:

1. May I ask how all the 1D arrays of your LET are scored in the protons_Generic base data file? Is it an average of the transverse slice? If so, what dimension are the vowels? And why are the LET values being scored in a 1D manner?
2. What particles are included in the simulation of LET, is it only the primary protons?
3. Is it possible to use MCsquare to score the LET and thereafter put the values into the custom file?
4. If I want to fill in the LET structure with LET values according to our machine parameters, how would you best advise me going about calculating these LET values?

Thank you very much in advance!

Best,
James

**Comment by wahln** [comment]
I need to check exactly how the LET values in protons_Generic where scored / computed next week. Maybe @becker89 or @markbangert remember it by heart.
We can re-engineer what _needs_ to be there
1. in https://github.com/e0404/matRad/blob/3d29b765a9a0a02a593890726102a7d9db907af7/matRad_calcCubes.m#L64-L67 the dose averaged LET get's computed from an "LET-influence matrix" which is stored within a cell array in `dij.mLETDose` 
2. in https://github.com/e0404/matRad/blob/3d29b765a9a0a02a593890726102a7d9db907af7/matRad_calcParticleDose.m#L273-L276 the entry for the beamlet ("bixel") get's computed from the machine data entry and the dephts in L273, and then multiplied with the dose in L267. 

With this, let's get back to your questions:

1. Whats stored in machine.data(:).LET, is "raw" depth-dependent LET (e.g. as you would compute using a CSDA). That's why it is stored 1D. It get's multiplied by the dose within all individiual beamlet voxels beamlet (becoming 3D LETd in the dij.mLETDose matrix), and then, after optimization and fluence weighting, averaged with the resulting dose. 
2. As said above, I need to check how it was computed next week. But in principle, you can decide how to define your LET simulation for your base data (i.e., scoring settings, particles included, etc.). You could even generate multiple datasets to compare.
3. It should be possible. I have never tried to score statistically sensible LET from MCsquare. We would also be interested in seeing if this works, to provide an example pipeline of how to create a matRad machine dataset with MCsquare. Let me know if you need some help.
4. See 1 & 2. In principle, make Monte Carlo simulations for individual beamlets. With MCsquare, you can't really set up radial scorers (I think), so you need to work with cubes. I guess averaging the LET in each orthogonal slice does the trick - the depth unit _should_ be mm.

I hope I didn't spread some alternative facts here late friday evening, and hope this helps with the initial steps for putting your LET into your machine data! Let me know if you have further questions!

**Comment by jeimzos** [comment]
Dear @wahln ,

Thank you and I very much appreciate your swift and concise reply. 

May I ask if you've managed to find out on your side the types of particles included in the simulation of your LET values in the generic base data file?

In a follow-up question: may I also ask if it is possible to recalculate the dose from an imported DICOM plan _without_ performing an optimization? I would like to simulate the LET from an imported DICOM plan after performing matRad's dose recalculation via the pencil beam algorithm, however it seems I always have to perform a re-optimization before being able to simulate the LET.

Thank you very much in advance!

Best regards,
James

**Comment by wahln** [comment]
Dear James,

regarding the first question - unfortunetaly, the generation of the protons_Generic dataset is sparsely documented, and the respective developers are no longer working on matRad. So I haven't figured it out fully yet. As the proton_Generic dataset is a pure analytical dataset (Based on Bortfeld 1997 & Gottschalk et al 1993 et al, see the matRad paper Wieser et al 2017), I am 95% sure it was also computed analytically based on the Bortfeld approximation, and I think I found parts of the code for that in our internal repositories. The details are not clear to me yet, but apparently it uses a finite difference computation on the analytical depth dose to obtain the LETd. So basically this can not be argued with a restriction on particle types. Sorry if this is a quite unsatisfying answer - you just should decide on your favorite definition/scoring rationale of LETd and not worry too much about representing what's already in protons_Generic.mat

Now to the more straightforward follow-up question: Yes, this should possible. After DICOM import, you should have the `stf` and the `pln` in your workspace. If yes, matRad can do a forward dose & LET calculation given the pencil-beam weights. The important thing is to set `pln.propDoseCalc.calcLET = true;` and then do either of two things:
1. `resultGUI = matRad_calcDoseDirect(ct,stf,pln,cst,w)` where `w` are the pencil-beam weights. You can also try to call it without the `w` since the [DICOM import might already have written the imported weights to the stf](https://github.com/e0404/matRad/blob/master/dicom/matRad_importDicomSteeringParticles.m).
2. do a normal dose influence matrix computation and afterwards use the matRad_calcCubes function: `dij = matRad_calcParticleDose(ct,stf,pln,cst); resultGUI = matRad_calcCubes(w,dij);`. Here, the weights `w` are required.

Let me know if this doesn't solve the issue.

**Comment by jeimzos** [comment]
Dear @wahln ,

Thank you so much again for your quick response. Unfortunately, I cannot seem to find the pencil-beam weights (w) after the DICOM import. I suspect I did not perform the DICOM import properly. Perhaps I shall explain how I did the DICOM import-

1. I followed the steps from [the wiki](https://github.com/e0404/matRad/wiki/The-dicom-import) successfully up to the point where I have to specify the base data of our machine - upon selecting the custom base data machine I previously created, I get these errors:

```
importing ct-cube...
creating info...Progress: 100.00 %
reading slices...Progress: 100.00 %

z-coordinates taken from ImagePositionPatient

Interpolating CT cube...finished!

conversion of ct-Cube to Hounsfield units...finished!

Reading structures...finished!
creating cube for BODY volume...
creating cube for 1. T1W_GTV volume...
creating cube for CTV volume...
creating cube for BRAINSTEM volume...
creating cube for CHIASM volume...
creating cube for CORD volume...
creating cube for EYE_LT volume...
creating cube for EYE_RT volume...
creating cube for LARYNX volume...
creating cube for OPTIC NERVE_LT volume...
creating cube for OPTIC NERVE_RT volume...
creating cube for PITUITARY volume...
creating cube for TEMPORAL LOBE_LT volume...
creating cube for TEMPORAL LOBE_RT volume...
creating cube for PTV 54/30# volume...
creating cube for LENS_LT volume...
creating cube for LENS_RT volume...
creating cube for ISOCENTER volume...
creating cube for OPT NERVE_LT 3mm volume...
creating cube for OPT NERVE_RT 3mm volume...
creating cube for CHIASM 3mm volume...
creating cube for _opt OL optics volume...
creating cube for _ring volume...
creating cube for _opt CTV volume...
creating cube for _opt BS volume...
finished!
Warning: Could not determine mass and atomic number of the particle 
> In matRad_importDicomRTPlan (line 106)
In matRad_importDicom (line 106)
In matRad_importDicomGUI>import_button_Callback (line 330)
In gui_mainfcn (line 95)
In matRad_importDicomGUI (line 53)
In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)matRad_importDicomGUI('import_button_Callback',hObject,eventdata,guidata(hObject)) 
Error using  * 
Incorrect dimensions for matrix multiplication. Check that the number of columns in the first matrix matches the number
of rows in the second matrix. To perform elementwise multiplication, use '.*'.

Error in matRad_importDicomSteeringParticles (line 158)
            (currEnergy * ones(numOfScanSpots,1)) weight_help (currFocus * ones(numOfScanSpots,1)) ...

Error in matRad_importDicom (line 116)
            [stf, pln] = matRad_importDicomSteeringParticles(ct, pln, files.rtplan);

Error in matRad_importDicomGUI>import_button_Callback (line 330)
matRad_importDicom(files, dicomMetaBool);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in matRad_importDicomGUI (line 53)
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)matRad_importDicomGUI('import_button_Callback',hObject,eventdata,guidata(hObject))

Related documentation
 
Error while evaluating UIControl Callback.
```

2. To circumvent this, I followed the solution in this [thread ](https://github.com/e0404/matRad/issues/416) where commenting out the stf portion was suggested, which solved the issue and I get a .mat file of my DICOM.

3. Following, I manually specified some pln parameters that were missing and generated the stf as follows:
```
pln.propDoseCalc.calcLET    = 1; 
pln.propStf.bixelWidth      = 3; 
pln.machine                 = 'CustomDicom';
stf = matRad_generateStf(ct,cst,pln);
```
4. Upon attempting matRad_calcDoseDirect(ct,stf,pln,cst,w), with and without 'w', I get an error due to an "unrecognized function or variable 'w' " or "No weight vector available. Please provide w or add info to stf" respectively.

I suspect by doing point 2 above I may have skipped over the bixel weight import from the DICOM files. May I ask for your advice to proceed from here? Apologies in advance for any inconvenience.

Best regards,
James

**Comment by wahln** [comment]
Ah okay, yeah when you skip the Plan import, you won't have the geometry / weights available. 
So it might be worthwhile to check what is not working during the import. Let me ask some stuff here:

The stf / weight import fails at a point where matRad tries to loop through the "IonControlPointSequence" in the RTPlan:
https://github.com/e0404/matRad/blob/3d29b765a9a0a02a593890726102a7d9db907af7/dicom/matRad_importDicomSteeringParticles.m#L130-L160

Particularly, it failes when accumulating the extracted information. Probably, something could not be extracted (i.e., the variable is empty) or has some different storage format than we expected given the files we used as benchmarks, and this is why you obtain the "incorrect dimensions" error.

Can you set a breakpoint in l. 157 in this file during import and check out the content / dimensions / datatype of the variables that get concatenated here? That is:

- c1_help 
- c2_help 
- currEnergy 
- numOfScanSpots
- weight_help 
- currFocus 
- rashiID 
- rashiWeThickness 
- rashiIsoRangeDist

I think that matRad expects all of these variables to be numeric scalars.
Also it would be nice to know if it fails directly the first time running, or at some particular later iteration through the for loop.

**Comment by jeimzos** [comment]
Here are the content / dimensions / datatype :

![image](https://user-images.githubusercontent.com/88191921/152384052-954a7069-5186-45a6-8091-6f9eb43b4c41.png)![image](https://user-images.githubusercontent.com/88191921/152384157-30e7b3c2-8156-4f9d-b6ba-f40a17234bf6.png)![image](https://user-images.githubusercontent.com/88191921/152384264-4bd55e01-c674-471c-8c20-ecd58fda5974.png)![image](https://user-images.githubusercontent.com/88191921/152384326-0649a4bc-70a5-45c5-a189-e06e5bf7e289.png)![image](https://user-images.githubusercontent.com/88191921/152384387-9490e899-fc1d-427b-a854-cb454bb0c621.png)
![image](https://user-images.githubusercontent.com/88191921/152384423-95683207-cfff-4b0d-bb7d-08d2343da1ef.png)![image](https://user-images.githubusercontent.com/88191921/152384492-7e662f74-db7b-4902-93fc-de0913930d87.png)![image](https://user-images.githubusercontent.com/88191921/152384562-87f0ae2a-63da-4c7f-9bf1-78c42246d9c6.png)![image](https://user-images.githubusercontent.com/88191921/152384590-efc76b80-2430-447c-81b0-cb363f3aceb9.png)

It does not fail directly the first time running, but only on the ~36th iteration through the for loop (right before it moves to l. 52)

**Comment by jeimzos** [comment]
Here are the content / dimensions / datatype on the ~36th iteration (before it errors out):

![image](https://user-images.githubusercontent.com/88191921/152388586-c7d6051a-d629-49dc-a55b-15f0f49be647.png)![image](https://user-images.githubusercontent.com/88191921/152388618-5a78aef5-cdf3-4d92-b8ac-dd0ea543cf20.png)![image](https://user-images.githubusercontent.com/88191921/152388673-86fdabe8-53fd-4deb-baca-47836082602d.png)![image](https://user-images.githubusercontent.com/88191921/152388707-5ef5954d-c96c-4554-892f-c53c0075f76f.png)![image](https://user-images.githubusercontent.com/88191921/152388754-7c32a8e8-7d21-4fd2-85d9-34fe005e3de0.png)
![image](https://user-images.githubusercontent.com/88191921/152388811-9d9cdd0d-32fe-448f-a1a1-9231d27f1d15.png)![image](https://user-images.githubusercontent.com/88191921/152388851-800705f7-633d-479e-aecb-ff703784b564.png)![image](https://user-images.githubusercontent.com/88191921/152388888-68d3713d-0978-4db2-8d47-8962cded312e.png)![image](https://user-images.githubusercontent.com/88191921/152388926-a1ecadc8-4ccc-43bd-8b36-e161d3bed61c.png)

**Comment by wahln** [comment]
Yes, the 2x1 currFocus is the issue. If I recall the DICOM Standard correctly, there's always two control points, and the second control point might have a changed value to represent the dynamics during delivery (but shouldn't have in a static delivery). We don't support this right now, as it somehow requires implementation of delivery dynamics. 

As the change here is quite miniscule, a possible workaround might be to replace  `unique` with `mean` in L135 (or force it to only extract the first value) to obtain a scalar value - it may have some consequences further down, as our implementation of spot sizes currently works with a indexed set of focus settings for each energy, and later, starting L270, try to assign these based on the extracted spot sizes.

Let me know if the workaround works. If you manage to go import scalar values only, but fail later at assigning foci, I may look for some way to work with a given FWHM instead of an index.

**Comment by jeimzos** [comment]
Yup, you are right. Replacing unique with mean solves the matrix issue, but I get another error further down as you've mentioned.. 

```
importing ct-cube...
creating info...Progress: 100.00 %
reading slices...Progress: 100.00 %

z-coordinates taken from ImagePositionPatient

Interpolating CT cube...finished!

conversion of ct-Cube to Hounsfield units...finished!

Reading structures...finished!
creating cube for BODY volume...
creating cube for 1. T1W_GTV volume...
creating cube for CTV volume...
creating cube for BRAINSTEM volume...
creating cube for CHIASM volume...
creating cube for CORD volume...
creating cube for EYE_LT volume...
creating cube for EYE_RT volume...
creating cube for LARYNX volume...
creating cube for OPTIC NERVE_LT volume...
creating cube for OPTIC NERVE_RT volume...
creating cube for PITUITARY volume...
creating cube for TEMPORAL LOBE_LT volume...
creating cube for TEMPORAL LOBE_RT volume...
creating cube for PTV 54/30# volume...
creating cube for LENS_LT volume...
creating cube for LENS_RT volume...
creating cube for ISOCENTER volume...
creating cube for OPT NERVE_LT 3mm volume...
creating cube for OPT NERVE_RT 3mm volume...
creating cube for CHIASM 3mm volume...
creating cube for _opt OL optics volume...
creating cube for _ring volume...
creating cube for _opt CTV volume...
creating cube for _opt BS volume...
finished!
Warning: Could not determine mass and atomic number of the particle 
> In matRad_importDicomRTPlan (line 106)
In matRad_importDicom (line 106)
In matRad_importDicomGUI>import_button_Callback (line 330)
In gui_mainfcn (line 95)
In matRad_importDicomGUI (line 53)
In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)matRad_importDicomGUI('import_button_Callback',hObject,eventdata,guidata(hObject)) 
Unable to perform assignment because the indices on the left side are not compatible with the size of the right side.

Error in matRad_importDicomSteeringParticles (line 279)
            stf(i).ray(j).focusIx(k) = focusIxTemp;

Error in matRad_importDicom (line 116)
            [stf, pln] = matRad_importDicomSteeringParticles(ct, pln, files.rtplan);

Error in matRad_importDicomGUI>import_button_Callback (line 330)
matRad_importDicom(files, dicomMetaBool);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in matRad_importDicomGUI (line 53)
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)matRad_importDicomGUI('import_button_Callback',hObject,eventdata,guidata(hObject)) 
279             stf(i).ray(j).focusIx(k) = focusIxTemp;
```

**Comment by wahln** [comment]
Ha, nice, we are getting close to the end of this import.

What we should do here kind of depends on how you have set up your base data file, particular the `initFocus` entries for all energies. 
- Do these contain multiple foci per energy? 
- Are the FWHM entries you obtain in the Loop above (corresponds to the `focusFWHM` in L276) in accordance with a `initFocus.SisFWHMatIso` in the base data entry for this energies
- Why does it fail in L278? (does it find more than one match or no match at all) --> That is, what does `focusIxTemp` contain at this point?

Something that might be helpful when dealing with errors in loops is Matlab's `dbstop if error` (in the command line before the import). It automatically enters debug mode if an error occurs.

**Comment by jeimzos** [comment]
- The entries for the initFocus (dist, sigma, SisFWHMAtIso) at each energy are actually those from matRad. I actually did not touch the values for this. Perhaps I should've also changed these entries according to our machine. May I ask how I can go about filling these in with our machine parameters?


- The values do not match. I guess not surprisingly so.

ie focusFWHM in the loop shows 17.8372, while the SisFWHMAtIso in the base data file for the first energy value is 11.7741 


- focusIxTemp shows an empty value

ie a 0x0 double. Perhaps this is why the following error at l. 279 shows up: 
"`Unable to perform assignment because the indices on the left side are not compatible with the size of the right side.`"
The for loop doesn't even pass the first iteration as it stops at l.279.

Here are some snaps, hopefully these give you a better picture of the problem at hand:

Current workspace:
![image](https://user-images.githubusercontent.com/88191921/152407765-9e1dd9b9-b2cb-473f-9f5e-3e16d965b708.png)
First row entry of our machine.data:
![image](https://user-images.githubusercontent.com/88191921/152407881-0d4f03e8-aba3-4a87-b20d-a8ff03d8eb72.png)
initFocus of our first row entry:
![image](https://user-images.githubusercontent.com/88191921/152407912-2ff47ea5-ca8c-4a1e-b3b8-01f14bfe5ff2.png)

**Comment by jeimzos** [comment]
Dear @wahln ,

Perhaps another alternative way to get the pencil beam weights 'w' is through hacking from, say, the DICOM RTPLAN meta data file as viewed via 3D slicer. To directly get the pencil-beam weight data from 3D slicer, and then manually creating a 'w' variable with said data. In that case, maybe you could let me know where exactly these pencil-beam weights correspond to in an arbitrary DICOM RTPLAN meta data file in 3D slicer.

Best regards,
James

**Comment by wahln** [comment]
So the weights won't help you much when you can't import the corresponding geometry. When you call `matRad_generateStf`, the created geometry (that is, spot positions / placmenent and consequently number of spots) will not be the same, and thus you won't be able to apply the weights. 

Also, the correct focus setting is important to have the correct beam optics when re-computing the dose.

The initFocus stores specific beam foci (i.e., spot widhts at isocenter). matRad expect that there is one or multiple foci you can set per energy. For each of these foci, matRad stores the
- FWHM at IsoCenter of the beam
- multiple measurements at distances from the isocenter to model the beam convergence / divergence

For your machine, you either may have such measurements for each beam focus setting per energy or some respective form of phase space parameterization, like a Bi-Gaussian emittance parameterization (width, correlation, momentum spread)?

**Comment by jeimzos** [comment]
Dear @wahln, 

I have since configured the initFocus file according to our machine.
I have also identified the error that occurs near the end of the code. 

On the 1st iteration of looping over all energies:
https://github.com/e0404/matRad/blob/3d29b765a9a0a02a593890726102a7d9db907af7/dicom/matRad_importDicomSteeringParticles.m#L270-L282
In Ln 278: focusIxTemp returns an empty array '[]'.
When this empty array is fed into stf(i).ray(j).focusIx(k) in Ln 279, the following error shows up:

`'Unable to perform assignment because the indices on the left side are not compatible with the size of the right side.' `

Which makes sense as feeding an empty array into an empty array (focusIx) will undoubtedly return an error.

I am just curious as to why this error occurs... Perhaps maybe I could get your insight on what exactly Ln 278 is trying to do? And maybe we may find out why it gives us an empty array.

**Comment by wahln** [comment]
Sorry for the late response - this line is trying to figure out the "focus index" by comparing the spot widhts from the DICOM RTPlan with those stored in the base data (basically the entry "SisFWHMAtIso" stores the FWHM, that is the spot width, for each focussing index for each energy at the isocenter, which should correspond to the DICOM attribute). The 10^-3 is then a "tolerance value" for this assignment. 
For testing purposes, you might override this with just setting `focusIxTemp = 1` isntead of executing this line. Then always the "first" focus setting will be selected.
