### ISSUE TITLE
Feature request: isocenter

### ISSUE THREAD

**Issue by markbangert** [e0404/matRad#55]
Show iso center in GUI by showing some cross hairs or similar...

**Comment by becker89** [comment]
Iso center cross hair is now part of the dev branch. Unfortunately it is not possible to set the opacity of markers. Therefore a cross is displayed in dark grey (still good visible when dose is displayed) when the current slice is not a iso dose slice - otherwise it will be shown in black. It was necessary to turn the OpenGL software rending to ensure a proper plotting order.
