### ISSUE TITLE
[BUG] Lag in GUI Update and Optimization call

### ISSUE THREAD

**Issue by TBurlacu-tud** [e0404/matRad#550]
**Describe the bug**
The GUI is lagging every time an input is set. 

Unclicking the "Auto" button for the isocenter and just clicking in the window where the isocenter values can be set makes the GUI lag. Moreover, there is a significant delay between clicking "Optimize" and the actual optimization commencing. This did not happen in the past and it did not start with the latest Mac update. 

I tried re-installing Matlab and downgrading the matRad version but that did not help. 

**Desktop:**
 - OS: MacOS 12.3
 - Environment & Version: Matlab 2022a
 - matRad Version: v.2.10.1

**Comment by wahln** [comment]
Thanks for the bug report. My initial question would be if you are using a very well resolved CT (0.5mm or below)? 
- The lag in GUI update is a problem with how the GUI in Matlab needs to be updated, i.e., at the moment it updates the full view including redrawing of the slice of the CT, which is unfortunately not that fast in Matlab. This will probably improve with the next update of the user interface which uses manually programmed widgets instead of the current version programmed with the GUI editor `guide` from Matlab
- Regarding the start of the optimization, we recently discovered that in _some_ cases Matlab seems to copy the whole dose influence matrix (i.e., the `dij` struct) when creating the anonymous function passed to the optimizer. It is not clear why this happens, as the matrix is not modified. We have a solution in the works for this, but it is not yet finalized.

**Comment by wahln** [comment]
There was another issue, which I just addressed in [21f6ff8](https://github.com/e0404/matRad/commit/21f6ff80c9a28eedafec8e533d527ef265f1959c) on the dev branch. For carbon ions (and thus usage of effect/RBExD-based optimization), estimating the initial weights took quite long with large number of voxels, due to multiple row-indexing operations in the sparse matrices (which are stored in CSC, making it quite inefficient). For my test-case, this meant an initialization time of 25(!) seconds, which is now 1.5 seconds.

**Comment by TBurlacu-tud** [comment]
@wahln Thanks for your answer.

No, I just load the liver phantom and hit calc. influence matrix and optimize right away. Nothing is changed from its default values. I tried checking out the dev branch but unfortunately that did not help with the GUI issue.

**Comment by wahln** [comment]
That is indeed weird. Is this also affecting other Matlab interactions or only the matRad user interface? If Matlab is affected, I found some somwhat older issues with Matlab being slow on MacOS in graphical user interface interaction https://de.mathworks.com/matlabcentral/answers/422244-why-do-buttons-apps-or-the-editor-in-matlab-respond-slowly-or-hang-on-macos
However, this could be a completely different issue, since the versions reported in this thread are different from yours.

I would have one other workaround/test: We are developing a more flexible GUI on the branch dev_classGUI. It is not yet tested thoroughly, but it uses a different method to build the GUI and manage interactions. You might try using this branch, maybe it works more smoothly, and if you could report the results back to us that would be great. Sorry to send you on such a scavenger hunt, but I can't really reproduce the issue.

**Comment by TBurlacu-tud** [comment]
@wahln Sorry for the late reply. I don't use Matlab extensively, so I can't comment on anything else within Matlab. I did notice a similar issue in another GUI that was based on Qt. Moreover, I did checkout the dev_classGUI branch but unfortunately the GUI behaved in the same way as before.

**Comment by wahln** [comment]
I am really quite clueless on why Matlab/matRad does not like your mac. I have heard of slow Matlab, but that was on macOS 11 & 10 and could be circumvented by launching matlab from the terminal. 
I can only suspect some Java issue (as Matlab uses quite a lot of Java for display) or OpenGL. Or there is some app running that interferes with the display (see the link above). 
You could also try connecting to a second monitor and check if it runs as slowly when displaying on the secondary monitor...
Sorry for not being of more help here...

**Comment by TBurlacu-tud** [comment]
@wahln That link proved to have the solution. It seems that a window snapping app called Rectangle was interfering with Matlab. Quitting the app returned MatRad to its original responsive GUI. Thank you!
