### ISSUE TITLE
Can you share the code to calculate proton base data[Feature Request] 

### ISSUE THREAD

**Issue by Erhushenshou** [e0404/matRad#554]
Can you kindly post out the code to generate proton base data using double gaussian model? I see there is code about mcsquare, but I don't know how we can use it. Thanks.

**Comment by wahln** [comment]
Which code about MCsquare are you refering to?

**Comment by Erhushenshou** [comment]
I mean the code to generate the proton base data for proton calculation. And I see a repo "McSquare", is this used to generate base data from McSquare? Or we can use McSquare for proton Monte Carlo calculation?

**Comment by wahln** [comment]
- Check this issue that has a lengthy discussion about the "Generic" base data and its generation
https://github.com/e0404/matRad/issues/336
- On the branch dev_varRBErobOpt, there is a function [matRad_fitBaseData ](https://github.com/e0404/matRad/blob/ea37a851a0f122789175b0764b49dd12183432e8/tools/matRad_fitBaseData.m) which prototypes fitting of a base data entry given a dose cube and beam information. This is a development branch, so it requires some effort to get this running, I guess.
- You can just run MCsquare from matRad by using matRad_calcParticleDoseMC. instead of matrad_calcParticleDose.
