### ISSUE TITLE
LEMIV _effect and _RBE*D for protons

### ISSUE THREAD

**Issue by ktkaamir** [e0404/matRad#682]
Hi, I start using MatRad, when I try to use, LEMIV _effect and _RBE*D for proton plans. I get a warning,   optimization is not possible for proton and only the physical dose will be calculated. does this mean we can't use it for protons plans or did I do something wrong? Thank you all.
regards
Ameer 
RT Lab CGU Taiwan

![image](https://github.com/e0404/matRad/assets/64243461/4e408d5b-817e-42f7-a29a-a41bf79249e4)

**Comment by wahln** [comment]
In the master version (lastest release and master branch), protons can only be optimized for physical dose or with constant RBE. LEM IV is only integrated for the supplied carbon ion dataset (due to the pencil-beam algorithm requiring precomputed alpha*dose and sqrt(beta)*dose kernels). If you look on the dev_varRBErobOpt branch, you can also optimize with variable RBE models. This will be part of our next release, matRad 3.

**Comment by ktkaamir** [comment]
I've been exploring LET optimization in matRad and expected to see a significant difference in the LET distribution within the target. However, my observations didn't show a notable contrast. Any insights on this? Also, could you provide information on the release date for matRad 3? I'm interested in exploring any new features or improvements.
regards
Ameer

![image](https://github.com/e0404/matRad/assets/64243461/513c0075-59b2-4e68-b546-a6ce92f06532)
![image](https://github.com/e0404/matRad/assets/64243461/7ac77877-863d-42ef-ab75-30af67c269f3)

**Comment by wahln** [comment]
Are you using any functionalities on a research branch for that or did you implement it yourself? Without more details (e.g. a script to run), it is difficult to judge what is going on. There is definitely some change in the LET distribution, it looks like the lower panel has less LET in the OAR.

matRad 3 is a bit delayed, but we hope to fully release it this winter.
