### ISSUE TITLE
@SG in calcLateralParticleCutOff

### ISSUE THREAD

**Issue by rizwindu** [e0404/matRad#81]
Hi

The function handle @SG in calcLateralParticleCuttOff is defined as:

`SG = @(vR,Sigma)((1/(2*pi*Sigma^2)).*exp(-(vR.^2)./(2*Sigma^2)));`

Should this not be

`SG = @(vR,Sigma)((1/(sqrt(2*pi)*Sigma)).*exp(-(vR.^2)./(2*Sigma^2)));`

for a Gaussian distribution? Unless there is a normalisation of some sort that I'm missing.

**Comment by markbangert** [comment]
@becker89 could you please comment!? I guess this has to do with the fact that this Gaussian is for radial symmetry which means it must accomodate a 2D normalization not just a 1D normalizaion or do we have a bug right here?

**Comment by rizwindu** [comment]
@markbangert the radial symmetry normalisation would explain it I think.

**Comment by becker89** [comment]
Hi, 
to clear things up: a single two-dimensional Gaussian for describing the lateral beam profile is defined as follows:
L= ((1/(sqrt(2*pi)*SigmaX)).*exp(-(x.^2)./(2*SigmaX^2))) * ((1/(sqrt(2*pi)*SigmaY)).*exp(-(y.^2)./(2*SigmaY^2)))
due to the radial symmetric one can set SigmaX = SigmaY which results in:
L = ((1/(2*pi*Sigma^2)).*exp(-(r.^2)./(2*Sigma^2)))
So the implementation is correct (see also in matRad_calcParticleDoseBixel). 
However naming the function handle SG is probably confusing. A better name for instance would be SG2D. 
Note that this function will be re-written in the near future to improve the lateral cutoff calculation. In the course of this change we will come up with less confusing variable names.

**Comment by markbangert** [comment]
Thanks @becker89 for clearing things up. I will close this issue! And: Looking forward to the new lateralCutoffCalculation :)
