### ISSUE TITLE
Verifying use of lateralCutoff in RayTracing code

### ISSUE THREAD

**Issue by rcorredorj** [e0404/matRad#83]
Hi,

It's been a while since the days I was using matrad very often, but now I'm again into it and I found something a bit strange. 

I'm running the matRad code as I checked it out today (dataset: TG119) without any changes (lateralCutoff=20). 

Please check the following image that corresponds to the volume generated by the radial distances of the 1st ray in the 1st beam, i.e. sqrt(isoLatDisX^2 + isoLatDistZ^2) after running this line https://github.com/e0404/matRad/blob/master/matRad_calcPhotonDose.m#L230: 
![beamlet](https://cloud.githubusercontent.com/assets/2558598/16613931/dc1d2510-436e-11e6-9a3a-bc8107a23daf.png)

In the left image I pointed with a red arrow a region that seems to be incomplete for that beamlet. Those points won't be used in the dose calculation. I checked that this comes from the rays preselection in the rayTracing function. 

In this line https://github.com/e0404/matRad/blob/master/matRad_calcPhotonDose.m#L183, the rayTracing function already gave some values and they are filtered only to use the non-NaNs. When I visualize the volume of the radDepth (depth for each voxel within the lateral cutoff region of every ray in the beam), I see that the same region pointed before with the arrow is missing (next image).

![volume](https://cloud.githubusercontent.com/assets/2558598/16614586/6751528e-4372-11e6-920d-30e1775914ac.png)

The black lines are at a distance of 40mm, thus that region missing should have non-NaN values if the lateral cutoff was set to 20. So, why the beamlet dose is cut off? 

I tried to be as clear as I could but please ask if there is something you do not understand in the text. I would appreaciate if someone could verify this. FW: @markbangert 

--
RaC

**Comment by markbangert** [comment]
Hi Rac,

thanks for your input. I think what you want to say is that the ray tracing truncates regions where we actually want to compute dose influence. I agree that this should not be the case but I am somewhat confused because I thought we made the two worlds to be inline. I dont have time right away but if the game tonight between Wales and Portugal is boring I will investiage or later this week ;)

Meanwhile @AlexS1992 do you have an idea?

BTW: Cool volume rendering, hehe...

**Comment by rcorredorj** [comment]
Great !! 

It's exactly what I wanted to say: "_ray tracing truncates regions where we actually want to compute dose influence_"

I'll keep  checking, if I find something else I'll tell you. I hope the match today won't be too boring, but for sure we will have a very good one tomorrow. This cup must be for Germany  :-D !!

**Comment by rcorredorj** [comment]
Hi,

Update: I checked the same matrices for other two cases and it seems that this effect is only caused by the approximations when the values are set in the voxel grid.

![braincase](https://cloud.githubusercontent.com/assets/2558598/16712965/50c64ed8-4698-11e6-9fe3-aabc3ad7c95d.png)
In this image the tumor is within the orange circle in left image. The target point of the first ray (first beam) is shown with a point in green.The image in the center is the lateral distances for that point with a cutoff that correctly matches (20mm). The image on the left is the zone produce by all the rays using the same cutoff, this one is obtained from the raytracing (the radDepth or the geoDist returned values are calculated in that space).

So it seems that everything remains good. If I find any issue I'll tell you. Thank you in any case and enjoy the euro final!!

Cheers,

RaC

**Comment by markbangert** [comment]
Hi Ricardo,

my apologies, I did not have the time yet to look into this. Unfortunately
there are multiple deadlines this month and things start loading up...

I am afraid I do not fully understand what you are saying in the last
message. Are you saying that we might do some faulty calculations that
relate to the conversion from mm to number of voxels? I dont think that
this should matter because in/exclusion of voxels is always handled
according to correct distance calculations in mm.

Or have you been able to resolve the issue completely ["everything reminas
good"].

Cheers / Mark

**Comment by markbangert** [comment]
Hi RaC,

so seems like the Portugiese football inspired my bug search skills... Really took me all afternoon but now I finally found the error! We forgot to project the distance calculation to the iso center when we considered the lateral cutoff to adjust the volume for ray tracing. As this is only a 10% correction which only effects the very border beamlets we did not really recognize this unwanted behaviour when we made all the changes in the ray tracing recently.

I made the corrections in the latest commit on the dev branch. I would appreciate if you could also have a look to confirm that this really fixes your problem.

--> changes in matRad_rayTracing.m in commit #606
https://github.com/e0404/matRad/commit/7e207c36cc3f13c898336c8883f20990279172c4

Will wait for your confirmation before closing this issue...

M

**Comment by rcorredorj** [comment]
That's great! 

My last message was not very clear indeed, but now this commit fixes that little bug. My point in the previous message was that the missing parts in the borders were mainly perceived in the TG119 case, most probably because the resolution of that volume is coarser (3x3x2.5), than the other cases I was trying with (1x1x1). The missing values were more evident in TG119 (the images in the first post) than the others (the images in my second post).

Now everything is working properly. Check the images for the TG119 after the fix:
![bugfixedraytracing](https://cloud.githubusercontent.com/assets/2558598/16762666/c08cca74-4825-11e6-8f88-1c312a080444.jpg)

I don't see why do you add the one to the ratio rayMx_bev_y/stf.SAD in the projection, but I'll try to check better the coordinates and the projections.

Euro cup finished (with an unexpected winner!) and another issue to be closed.

Thanks!

RaC

**Comment by markbangert** [comment]
Hey RaC,

(rayMx_bev_y/stf.SAD+1) = (stf.SAD + rayMx_bev_y)/stf.SAD

which is the factor you need to correct for in order to project from the isoCenter to the plane of the ray matrix.

JFTR: Now the consideration of the lateral cutoff is exactly met in the isocenter plane for every beam direction. Down and upstream of the iso center plane there are deviations according to the projection - especially for particles with large SAD that should barely make any difference. We talked this through yesterday and came to the conlcusion that the overhead of a full volume distance calculation is not justified at this point and that this slight approximation makes sense in order to keep speed high.

Cheers / Mark
