### ISSUE TITLE
New proton beam parameterisation

### ISSUE THREAD

**Issue by rizwindu** [e0404/matRad#90]
Hi

I'm using matRad to experiment with a new parameterisation for a proton beam (i.e., not using Gaussians). At the moment, my implementation adds a few lines of code to calcLateralParticleCutOff and calcParticleDoseBixel. I'm happy to share my code back in the future but have noticed some changes to these two functions on the dev branch. Are any major updates planned that may change the way either of these functions work?

Ben

**Comment by markbangert** [comment]
Hi Ben,

thanks for getting in touch.

You are right, we made some changes in the dev branch. Everything relating
to calcLateralParticleCutoff restructuring of the code there are no severe
conceptual changes. In the calcParticleDose we added funcationalies to
calculate dose averaged LET because we have a couple of people being
interested in that here in Heidelberg. Again this does not mean any severe
changes just an addition so I think you can go ahead with your developments
without getting out of sync with the matRad main version in the near future.

What might be interesting for you, however, is that we are experimenting
with a dose influence matrix sampling startegy to reduce memory consumption
(compare http://www.ncbi.nlm.nih.gov/pubmed/12033562).

Please let me know if you need any more information - if not I would close
this issue.

Also be informed that we have a matRad newsletter that we send out on an
irregualr basis that informs about changes of the code. If you want you can
send me an email to m.bangert at dkfz.de and I'll include you in the
mailing list.

Cheers / Mark

**Comment by rizwindu** [comment]
Hi Mark

Thank you for the quick and informative reply.

The dose influence matrix sampling strategy looks interesting. I look forward to updates around this in the future.

I will email you regarding the newsletter.

Best wishes

Ben
