### ISSUE TITLE
Keeping/Storing CT in HU

### ISSUE THREAD

**Issue by wahln** [e0404/matRad#98]
I think we should think of keeping the CT in hounsfield units along with the electron density and also add them to the existing mat-files. 
I think this would be better for an interface (exporting whole patients etc) to other systems like MITK etc
Also the interpolation with the given HLUTs is in general more convenient CT -> ED than ED ->CT 
Also we then could provide a CT colormap which is more common for many people.
What is the opinion on that?

**Comment by becker89** [comment]
In general, my answer is yes because it is more intuitive to see CT numbers instead of ED values.  But this is also a question of software design. Do we want to have matRad as "light-weighted" as possible or not. 
We could provide some sort of backup solution if CT images (especially time resolved CT images) are consuming too much memory. We could always hold both cubes or both cube series in ct.cube{ix} and the interpolated cube in ct.ED{ix}. If we consume to much memory then we simply do not store ct.cube and visualise the ct.ED cube as we do now.

**Comment by markbangert** [comment]
I agree with all agruments made by Niklas. We should think about a transition from _relative_ elctron densities to HUs. However, that triggers a couple of changes in program design and we need to thoroughly think this through together before we rush into something.

For the time being, Niklas, you can de-engineer the transformation for export because the HLUT is stored as part of the original DICOM information in the ct struct .

**Comment by markbangert** [comment]
Argh.. I just accidentally merged @Haydnspass pull request into the dev branch. I fixed some minor bugs on it and revised the GUI layout a little bit, though.

But there were two things I wanted to discuss first. Anyway: I am not going to revert things so let's try to settle the issues here:

@becker89 I think I have found an outdated artefact in the code when deleting 'set(handles.popupmenu_windowPresets,'Visible','on');' in commit https://github.com/e0404/matRad/commit/4cf958a84d746259ab16895565bba35ac4b2348c. Could you please confirm that this is not used?!

@Haydnspass When we have both HU and eDens cubes i have the options 'None' and 'HU' for display in the pull down menu on the right. What does 'None' mean? Shouldn't this be eDens? And for me the colorbar does not update. I think there is still some but in here?!

**Comment by Haydnspass** [comment]
@markbangert 

- (originally @becker89) 'set(handles.popupmenu_windowPresets,'Visible','on');' was added by me in order to enable / disable the dropdown menu when (no) ct cube in HU is available. The descriptive text above the dropdown menu should also change to 'window presets are not available' or something similar.

- ehm, I just kept this as it was made by @wahln, None means that the colour bar next to the actual window is disabled, so the window is slightly bigger. The text for ct should change from CT (ED) to CT(HU) in case HU values are used.

**Comment by markbangert** [comment]
And regarding the issue with popupmenu_windowPresets:

I am somewhat confused here because when I include it I get the error message 'Reference to non-existent field 'popupmenu_windowPresets'.' which indicates that there is some initialization missing...

**Comment by Haydnspass** [comment]
Eh, this popupmenu thing is deprecated, sorry for that. Corrected the colorbar description.
--> https://github.com/e0404/matRad/pull/130
